### ISSUE TITLE
applying (squeeze, clean, compress,..etc) to attachements of pdf type

### ISSUE THREAD

**Issue by maadjordan** [johnwhitington/cpdf-source#101]
Cpdf to check for internally attached pdf and expose them to cpdf general commands (as mentioned above) so these commands will run recursively to main file and its internal attached pdf files.

After testing with v2.2 I am getting error.

sample file: http://www.arvindguptatoys.com/arvindgupta/paper-polyhedra.pdf
- after optimizing file is ok (with -squeeze command)
- making two copies of same file with different names
- attaching these file to the optimized file is ok (I made another sample with 1 file attached and another with 2 files attached)
- optimizing result file will give error 
[double attachment error.txt](https://github.com/johnwhitington/cpdf-source/files/1184806/double.attachment.error.txt)
[single attachment error.txt](https://github.com/johnwhitington/cpdf-source/files/1184807/single.attachment.error.txt)

Also is there a command to extract attachments?

**Comment by johnwhitington** [comment]
Thanks.

Please show the command you used to attach the files.

cpdf -dump-attachments in.pdf

(Currently undocumented)

The idea of allowing the squeezing of attached PDF files is interesting.

**Comment by maadjordan** [comment]
cpdf -attach-file first.pdf -attach-file second.pdf original.pdf -o new.pdf

**Comment by johnwhitington** [comment]
I cannot replicate the problem in your first comment:

```
gorge:poly john$ cpdf -squeeze paper-polyhedra.pdf -o squeezed.pdf
Initial file size is 2626880 bytes
Beginning squeeze: 551 objects
Squeezing... Down to 373 objects
Squeezing page data and xobjects
Recompressing document
Final file size is 344909 bytes, 13.13% of original.
gorge:poly john$ cp paper-polyhedra.pdf 1.pdf
gorge:poly john$ cp paper-polyhedra.pdf 2.pdf
gorge:poly john$ cpdf -attach-file 1.pdf -attach-file 2.pdf squeezed.pdf -o attached.pdf
gorge:poly john$ cpdf -squeeze attached.pdf
Initial file size is 946457 bytes
gorge:poly john$ cpdf -squeeze attached.pdf -o out.pdf
Initial file size is 946457 bytes
Beginning squeeze: 377 objects
Squeezing... Down to 375 objects
Squeezing page data and xobjects
Recompressing document
Final file size is 645580 bytes, 68.21% of original.
gorge:poly john$ cpdf -attach-file 1.pdf squeezed.pdf -o attached.pdf
Beginning squeeze: 375 objects
Squeezing... Down to 374 objects
Squeezing page data and xobjects
Recompressing document
Final file size is 645536 bytes, 99.96% of original.
gorge:poly john$ cpdf -attach-file 1.pdf -attach-file 2.pdf paper-polyhedra.pdf -o attached.pdf
gorge:poly john$ cpdf -squeeze attached.pdf -o out.pdf
Initial file size is 1001279 bytes
Beginning squeeze: 386 objects
Squeezing... Down to 376 objects
Squeezing page data and xobjects
Recompressing document
Final file size is 645601 bytes, 64.48% of original.
```

Can you provide an exact series of commands, starting with just `paper-polyhedra.pdf` which replicates the bug?

**Comment by maadjordan** [comment]
strange,  I tried it today and its ok I am using windows 10 pro creators update ..
