### ISSUE TITLE
Some PDF Pages auto rotates to landscape when Scaled 

### ISSUE THREAD

**Issue by gchaitu2** [johnwhitington/cpdf-source#102]
Hi,

Some of the PDF pages were being auto rotated to landscape while scaling down the PDF file using, cpdf -scale-to-fit "215.9mm 279.4mm" in.pdf -o out.pdf.

Is there an option / command so that the pages do not get auto rotated to landscape.

With thanks
Chaitanya

**Comment by johnwhitington** [comment]
You've provided landscape page size "215.9mm 279.4mm". Do you want cpdf to simply ignore the pages which are not landscape?

Perhaps if you could provide an example file I could understand better...

**Comment by gchaitu2** [comment]
Actually the dimensions 215.9mm 279.4mm equal to 8.5 x 11 in inches Letter format Portrait as per standard. And my requirement is to scale down all the pages in a PDF file to 8.5 x 11 inches (Letter size). Even the landscape should be scaled to Portrait format (Content may shrink in this case but that is fine). Given A3,A4 sizes etc. should be scaled down to Letter size 8.5 x 11.

As you requested for a sample document, I am attaching a PDF document which after scaling it, using the below command, the pages from 10-88 are getting rotated/ resized to Landscape automatically, I think this is due to that page orientation setting (Rotation) of 90 degree.

Command: **cpdf -scale-to-fit "215.9mm 279.4mm" in.pdf -o out.pdf**
[PagesAutoRotated.pdf](https://github.com/johnwhitington/cpdf-source/files/1207788/PagesAutoRotated.pdf)

**Comment by johnwhitington** [comment]
Am away from the office for a while. Preprocess your file with -upright. Will give longer comments later...

**Comment by gchaitu2** [comment]
Hi John,

Thanks for your suggestion and it did worked well, now the pages were just as they were in original document. May I know why they were rotated, Also, will there be any post effects accessing the PDF file after this process.

With regards,
Chaitanya

**Comment by johnwhitington** [comment]
There are no aftereffects of processing the file in this way. What -upright does is to rotate the contents of the pages and counter-rotate the page dimensions so that the file looks exactly the same, but has no rotated pages.

**Comment by gchaitu2** [comment]
Hi John,

Thanks for the confirmation

With regards,
Chaitanya
