### ISSUE TITLE
UTF-8  bookmarks outline file with Cyrillic not accepted.

### ISSUE THREAD

**Issue by hermolaou** [johnwhitington/cpdf-source#103]
Here is a bookmark file with UTF-8 Cyrillic text.

It is created in Windows 10 Notepad.
The cpdf response is: Bad bookmark file (syntax) at line 0.

But removing the first three bytes from the file and trying again, it works.

[outline1.txt](https://github.com/johnwhitington/cpdf-source/files/1228416/outline1.txt)

**Comment by johnwhitington** [comment]
The first three bytes are the unicode byte-order-mark.

A simple solution is for cpdf to skip them, and assume UTF8. I will do this to begin with. Whether we need a more sophisticated solution I don't know.
