### ISSUE TITLE
Extend padding options to better support double-sided printing

### ISSUE THREAD

**Issue by python33r** [johnwhitington/cpdf-source#104]
cpdf is the best PDF manipulation tool I've come across, but doesn't quite do everything I need. I have a use case where I'm merging multiple PDFs into one and I need the first page of each constituent document to be the right-hand page when the merged document is printed double-sided.

From the docs, it seems like this isn't achievable currently. It could perhaps be supported via a ``-pad-even`` option that adds a blank page if necessary to each constituent document, so that it has an even number of pages.

**Comment by johnwhitington** [comment]
I can't think how to do it in a single command, but if you can check the number of pages to see which files need processing and only run the command on those, this should work:

cpdf in.pdf -pad-multiple 2 AND -range end,1-~2 -o out.pdf

(untested. it pads to a multiple of 2 pages (by padding at the end) then moves the padding page to the front)

Let me know how you get on...

**Comment by python33r** [comment]
``-pad-multiple`` gets me most of the way there - thanks!

Since it doesn't pad if the number of pages is already even, I can just run it on all input docs before doing the merge.

I've got it all working now in a relatively small Python script.

**Comment by johnwhitington** [comment]
Great. I'll keep this bug report open, since we might decide to add -pad-multiple-at-beginning in some future version.

**Comment by johnwhitington** [comment]
Wish granted in forthcoming v2.3 with -pad-multiple-before
