### ISSUE TITLE
support unicode in file name

### ISSUE THREAD

**Issue by maadjordan** [johnwhitington/cpdf-source#108]
I've noticed that if i renamed the "cpdfmanual.pdf" and use Russian, Hebrew or Arabic, it will not process it and "Invalid argument" error is given.

**Comment by johnwhitington** [comment]
The next version of OCaml (4.06.0) which is due out soon, has support for unicode filenames under Windows. So, the next cpdf will have this support be default.

Until then, I'm afraid the only workaround is to rename such files.

**Comment by maadjordan** [comment]
Then kindly provide a new compile of latest cpdf version based on OCaml (4.06.0) released.

**Comment by maadjordan** [comment]
Can you kindly recompile cpdf with latest ocaml as v 4.06.0 has been released officially? .. also can you provide the 64bit too?

Regards

**Comment by johnwhitington** [comment]
Version 2.3 will be 64 bit, unicode-supporting be default.

**Comment by maadjordan** [comment]
is there a release date for v2.3.. i saw October 2019 in source code
