### ISSUE TITLE
Out of Memory

### ISSUE THREAD

**Issue by maadjordan** [johnwhitington/cpdf-source#109]
Is it possible to increase the memory limit or to add an option to control it as i tried to process a huge file (over 500mb) and it ran with "out of memory" error.

**Comment by johnwhitington** [comment]
What platform is this on? On Linux and Mac, cpdf will use the whole memory of the machine if it can, on Windows the 32bit memory limit will prevent more than about 2gb being used, I think.

Can you share the file and the command?

**Comment by maadjordan** [comment]
its on windows and i used 

cpdf -compress -no-preserve-objstm -remove-duplicate-streams -fix-prince -remove-duplicate-fonts  -remove-metadata -no-embed-font -squeeze

I found a tool to patch an existing exe file http://nikkhokkho.sourceforge.net/static.php?page=PatchPE
I will try it and come back to you

**Comment by johnwhitington** [comment]
Thanks.

If you give me your email address, I can send you a 64 bit Windows build to try. We supply these to commercial customers, but don't routinely supply them with the community edition. This may change for the next release, though.

**Comment by maadjordan** [comment]
its my name @yahoo.com

**Comment by maadjordan** [comment]
is there an updated 64bit file and will it be official
