### ISSUE TITLE
Mac: Crashes on Opening

### ISSUE THREAD

**Issue by MarjaE2** [johnwhitington/cpdf-source#113]
cpdf crashes on opening:

[file path] ; exit;
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

**Comment by MarjaE2** [comment]
Using 10.12.6

Installed by copying the file to my Applications folder; that's all the instructions refer to.

**Comment by johnwhitington** [comment]
Hi,

Cpdf is a command line program, not a graphical application. Search “mac run command line program” on google for more details...

Thanks
