### ISSUE TITLE
Could not read object whilst reading file channel at position 366383

### ISSUE THREAD

**Issue by compn** [johnwhitington/cpdf-source#114]
sample file causes error in cpdf:
[33-lotan2014.pdf](https://github.com/johnwhitington/cpdf-source/files/1592161/33-lotan2014.pdf)

cpdf Version 2.2 (patchlevel 1, build of 1st September 2017)

cpdf -info 33-lotan2014.pdf
cpdf encountered an error. Technical details follow:

Could not read object whilst reading file channel at position 366383

Encryption: Not encrypted
Permissions:
Linearized: true
Version: 1.4

**Comment by johnwhitington** [comment]
The file is malformed. It looks like it was transferred over FTP in text mode, rather than binary. Other PDF processors (qpdf, ghostscript) agree, but seem to be able to resurrect the file.

So, I will keep this open to see if our malformed file restoration can be improved, but you should:

a) If you have control over the source of these files, get the problem fixed upstream; the files are genuinely malformed, and in a way which could change their printed contents (though from a quick inspection, that does not seem to be the case with this particular one)

b) If you don't have control over the source of the files, preprocess with another tool to mend them before using cpdf.


```
gorge:Desktop john$ qpdf 33-lotan2014.pdf out.pdf
WARNING: 33-lotan2014.pdf (object 50 0, file position 366375): expected endobj
WARNING: 33-lotan2014.pdf (object 1 0, file position 367424): expected endobj
WARNING: 33-lotan2014.pdf (object 5 0, file position 368486): expected endobj
WARNING: 33-lotan2014.pdf (object 8 0, file position 369548): expected endobj
WARNING: 33-lotan2014.pdf (object 125 0, file position 365521): stream keyword followed by carriage return only
WARNING: 33-lotan2014.pdf (object 127 0, file position 365630): stream keyword followed by carriage return only
WARNING: 33-lotan2014.pdf (object 129 0, file position 365739): stream keyword followed by carriage return only
WARNING: 33-lotan2014.pdf (object 132 0, file position 365997): stream keyword followed by carriage return only
WARNING: 33-lotan2014.pdf (object 134 0, file position 366674): stream keyword followed by carriage return only
WARNING: 33-lotan2014.pdf (object 136 0, file position 366783): stream keyword followed by carriage return only
WARNING: 33-lotan2014.pdf (object 138 0, file position 366892): stream keyword followed by carriage return only
WARNING: 33-lotan2014.pdf (object 140 0, file position 367150): stream keyword followed by carriage return only
WARNING: 33-lotan2014.pdf (object 142 0, file position 367736): stream keyword followed by carriage return only
WARNING: 33-lotan2014.pdf (object 144 0, file position 367845): stream keyword followed by carriage return only
WARNING: 33-lotan2014.pdf (object 146 0, file position 367954): stream keyword followed by carriage return only
WARNING: 33-lotan2014.pdf (object 148 0, file position 368212): stream keyword followed by carriage return only
WARNING: 33-lotan2014.pdf (object 150 0, file position 368797): stream keyword followed by carriage return only
WARNING: 33-lotan2014.pdf (object 152 0, file position 368906): stream keyword followed by carriage return only
WARNING: 33-lotan2014.pdf (object 154 0, file position 369015): stream keyword followed by carriage return only
WARNING: 33-lotan2014.pdf (object 156 0, file position 369273): stream keyword followed by carriage return only
qpdf: operation succeeded with warnings; resulting file may have some problems

gorge:Desktop john$ pdf2ps 33-lotan2014.pdf 
   **** Error: Missing whitespace after 'endobj'.
               Output may be incorrect.
   **** Error: Missing whitespace after 'endobj'.
               Output may be incorrect.
   **** Error: Missing whitespace after 'endobj'.
               Output may be incorrect.
   **** Error: Missing whitespace after 'endobj'.
               Output may be incorrect.
   **** Error: stream operator isn't terminated by valid EOL.
               Output may be incorrect.
   **** Error: stream operator isn't terminated by valid EOL.
               Output may be incorrect.
   **** Error: stream operator isn't terminated by valid EOL.
               Output may be incorrect.
   **** Error: stream operator isn't terminated by valid EOL.
               Output may be incorrect.
   **** Error: stream operator isn't terminated by valid EOL.
               Output may be incorrect.
   **** Error: stream operator isn't terminated by valid EOL.
               Output may be incorrect.
   **** Error: stream operator isn't terminated by valid EOL.
               Output may be incorrect.
   **** Error: stream operator isn't terminated by valid EOL.
               Output may be incorrect.
   **** Error: stream operator isn't terminated by valid EOL.
               Output may be incorrect.
   **** Error: stream operator isn't terminated by valid EOL.
               Output may be incorrect.
   **** Error: stream operator isn't terminated by valid EOL.
               Output may be incorrect.
   **** Error: stream operator isn't terminated by valid EOL.
               Output may be incorrect.
   **** Error: stream operator isn't terminated by valid EOL.
               Output may be incorrect.
   **** Error: stream operator isn't terminated by valid EOL.
               Output may be incorrect.
   **** Error: stream operator isn't terminated by valid EOL.
               Output may be incorrect.
   **** Error: stream operator isn't terminated by valid EOL.
               Output may be incorrect.
```

**Comment by compn** [comment]
i figured it was damaged in some way. but it does display ok in other pdf tools...
this was the only file that gave me trouble with cpdf , out of hundreds, so i figured it was worth reporting. not a priority for my needs, like you said, maybe useful in enhancing the error recovery in cpdf.

i was only using cpdf -info *pdf | grep -i pages to get page totals for all pdfs. i didnt really need to do anything else with this particular file. so in my case i dont need to fix it.

but i do appreciate the explanation and analysis.
thanks! cpdf is a very useful tool that can be scripted to my needs.

**Comment by kurmanka** [comment]
Hi, we have a similar case with a malformed document, where it breaks with 

> Attempting to reconstruct the malformed pdf 67741.pdf...
> list length 0
> list length 0
> list length 0
> list length 2
> EndStream
> endobj
> list length 0
> Read 1051 objects
> cpdf encountered an error. Technical details follow:
> 
> Failed to read PDF - initial error was
> Pdf.PDFError("Could not read object whilst reading file 67741.pdf at position 367652")
> 
> final error was
> Pdf.PDFError("No /Root entry whilst reading file 67741.pdf at position 2889292")
> 
>  whilst reading file 67741.pdf at position 2889292

Similarly, it happens on versions 2.2 (patchlevel 1, build of 1st September 2017) and Version 2.2 (build of 9th January 2017). But, in our tests, it only happens on 32-bit linux systems, and does not happen on 64-bit linux systems that we have around.

The file in question: [67741.pdf](https://github.com/johnwhitington/cpdf-source/files/1744159/67741.pdf)

Should i create another issue for that? or attaching it here is enough?

Thank you.

**Comment by kurmanka** [comment]
I just want to mention, that piping the document through qpdf didn't produce any error messages, but didn't help either — cpdf breaks in the same way on the qpdf-resulting document.

**Comment by johnwhitington** [comment]
It seems to work here, using the latest development cpdf on OS X. I tried:

`
cpdf -add-text "foo" 67741.pdf -o out.pdf
`

to test it. What command were you running?

It seems more likely to me that the 32 bit linux binary we last produced was out of date in some way, rather than that there is something about the 32bit environment causing the bug.

Are you using the demo version of cpdf from our website, or the community edition?

If you will be buying cpdf, we can provide a new executable for you. Otherwise, you'll have to build it yourself or wait for the next release.

**Comment by kurmanka** [comment]
John, the company we are working for has purchased a licensed version on Wednesday, March 22, 2017. I have just sent an email with some details to contact@coherentgraphics.co.uk.

cpdf fails with the above-quoted error if you simply run 
> $ cpdf 67741.pdf

**Comment by kurmanka** [comment]
I've just tried the demo version from your website and it fails in the same way:

> s@a:~/tmp/cpdf-fail-19-feb-2018$ cpdfdemo/cpdf /tmp/67741.pdf 
> This demo is for evaluation only. http://www.coherentpdf.com/
> Attempting to reconstruct the malformed pdf /tmp/67741.pdf...
> list length 0
> list length 0
> list length 0
> list length 2
> EndStream
> endobj
> list length 0
> Read 1051 objects
> cpdf encountered an error. Technical details follow:
> 
> Failed to read PDF - initial error was
> Pdf.PDFError("Could not read object whilst reading file /tmp/67741.pdf at position 367652")
> 
> final error was 
> Pdf.PDFError("No /Root entry whilst reading file /tmp/67741.pdf at position 2889292")
> 
>  whilst reading file /tmp/67741.pdf at position 2889292
> 
> s@a:~/tmp/cpdf-fail-19-feb-2018$

**Comment by johnwhitington** [comment]
It looks like it has been fixed in development already, unless there is something really obscure going on.

What platform are you using? I will send you a new executable...

**Comment by kurmanka** [comment]
John, for us this issue has been resolved off-github (via email) back then in February 2018.
