### ISSUE TITLE
cpdf and cyrillic 

### ISSUE THREAD

**Issue by grylem** [johnwhitington/cpdf-source#115]
Hi,
cpdf don't set title with cyrillic
cpdf -info dont show info with cyrillic
Regards

**Comment by johnwhitington** [comment]
Can you supply an example file, please?

**Comment by grylem** [comment]
I'm sorry, I was wrong. I tried set title from command file. If i set from command line argument title etc. set correct but anyway cpdf dont show info with cyrillic.
[test.zip](https://github.com/johnwhitington/cpdf-source/files/1645744/test.zip)

**Comment by johnwhitington** [comment]
Please try:

`cpdf -info -utf8 test.pdf`

**Comment by grylem** [comment]
Thanks.
