### ISSUE TITLE
[feature request] remove objects outside cropbox/hardbox

### ISSUE THREAD

**Issue by aseifert** [johnwhitington/cpdf-source#116]
Hello,

first of all I want to say thank you for all the great work that went into cpdf, it's really a delight to use! I have only recently stumbled upon this tool after searching for a way to crop pdfs to a given area, and I believed your "hard crop" feature is what I need. Sadly, I now think it's not exactly that, so I'm treating this as a feature request.

Here's my use case: I have been looking for a really long time for a cropping feature that doesn't just adjust the /CropBox, but REALLY deletes (or at least corrupts) the information outside the cropping area. I need this for two reasons: First and foremost, licensing issues allow me to use only parts of a page (a certain paid for article on a given newspaper page). If there's no other option then it *might* be okay to have the text hidden but inaccessible, but as I need to place that PDF on another page, I absolutely can't have the text reappear or be available to copy&paste. Second, I want to shrink the file size by deleting unnecessary images/objects.

Here's what I do now:

```
cpdf -crop '49.35pt 1323.84pt 167.79pt -882.56pt' -o cropped.pdf input.pdf
cpdf -hard-box '/CropBox' -o hard-cropped.pdf cropped.pdf
cpdf -remove-crop -o uncropped.pdf hard-cropped.pdf
```

The `uncropped.pdf` now has all other articles blanked out, which is good, but they are still selectable and I'm still able to copy&paste them, and also the file size could still be reduced by removing superfluous images.

Is a feature for this kind of use case planned, or is this out of scope? If it's the latter, do you have any idea of how I could achieve this? I would be really thankful if you could point me in the right direction.

Thanks a lot,
Alexander

[input.pdf](https://github.com/johnwhitington/cpdf-source/files/1719280/input.pdf)

**Comment by johnwhitington** [comment]
> I would be really thankful if you could point me in the right direction.

"PDF redaction" is the name of what you're looking for, and it's a well-known thing in legal circles, I believe, so you should be able to find something.

It's not something we're planning I'm afraid.

**Comment by johnwhitington** [comment]
Note that if you hard-crop a file in cpdf, and then stamp it onto another file, the cropped text shouldn't reappear, or be copy-and-pastable (unless the PDF reader is bad). But it will always still be present internally.

**Comment by aseifert** [comment]
Thanks for the quick reply, now I finally know the correct term! Sadly my use case is probably a little bit more special, as I need to retain the original PDF as much as possible, which forbids for example rasterizing the PDF, as we would lose a lot of information and file size might even increase.

As for your last point: I might be doing something wrong, but the text definitely becomes selectable again on my computer (Mac OS 10.13.3 , Preview 10.0) if I stamp it on a white page:

```
convert -size 1076x1665 canvas:white white.pdf
cpdf -stamp-on hard-cropped.pdf white.pdf -o stamped.pdf
```

I am using the steps described in the original post to arrive at the `hard-cropped.pdf`. Here's a screenshot of the resulting `stamped.pdf` in my PDF viewer:

<img width="597" alt="stamped-in-osx-preview" src="https://user-images.githubusercontent.com/4944799/36200557-666168ac-117d-11e8-992b-d2174bf66d14.png">



Thanks in advance,
Alex

**Comment by johnwhitington** [comment]
Right, it looks like your PDF viewer allows text occluded by a clipping box to be selectable. That's not how I'd write a PDF viewer, but the standard doesn't preclude it. So I think you need a real redaction solution.
