### ISSUE TITLE
one invalid bookmark corrupts all

### ISSUE THREAD

**Issue by grr** [johnwhitington/cpdf-source#123]
I have an ebook that appears to have a single bad bookmark (the "Index" in the table of contents). All other pdf readers I've tried (OS X Preview, Skim.app, Firefox's PDF.js, `mutool show outline`) work fine with the rest of the bookmarks, except the last one, the "Index" link is inactive since the destination is invalid.

But using cpdf with -list-bookmarks or any other operation with a page range, will result in a bunch of warnings like:

    Warning: Could not read destination G [4351 0 R/XYZ 53 633]
    Warning: Could not read destination G [5766 0 R/XYZ 35 338]
    ...
    Warning: Could not read destination D 9781484200537_Index.indd:Ind1

and the resulting output file will have all it's bookmarks pointing to the wrong place. Most point to page 0 so the table of contents don't even display those anymore. I tried `-clean` on the file first, but had no effect on this issue.

Example file: [Beginning Python Visualization, 2nd Edition - 2014.pdf](https://github.com/johnwhitington/cpdf-source/files/1886748/Beginning.Python.Visualization.2nd.Edition.-.2014.pdf)

**Comment by johnwhitington** [comment]
Preserving malformed bookmarks is an existing area of concern. It should be possible to round-trip any and all bookmarks through -list-bookmarks/-add-bookmarks and other operations. This will be done for the next release.

**Comment by johnwhitington** [comment]
(if you have an existing support contract, please let me know by email)

**Comment by johnwhitington** [comment]
Fixed in forthcoming v2.3

The ones like this:

Warning: Could not read destination G [4351 0 R/XYZ 53 633]

are indeed malformed. I have made cpdf more robust to them.

The one like this:

Warning: Could not read destination D 9781484200537_Index.indd:Ind1

Is in fact fine (it just points out-of-file)

I have extended cpdf to support such destinations.
