### ISSUE TITLE
Allow retaining of original page labels when using page range

### ISSUE THREAD

**Issue by grr** [johnwhitington/cpdf-source#124]
Currently when I want to remove some pages from a pdf I do something like from the manual: `cpdf in.pdf 1-16,18-25,29-150 -o out.pdf`. This keeps the page numbers of the remaining pages so bookmarks still work, but the page labels of the removed pages are still used so the table of contents show pages numbers that correspond to neither the logical or physical page of the bookmark destination. Using the above example, 5 pages are excluded from `out.pd`, so if a bookmark in the table of contents from `in.pdf` pointed to physical page 110 with page label 100, the resulting bookmark in `out.pdf` will correctly point to physical page 105, but will have the incorrect label 95 instead of the expected label 100.

**Comment by johnwhitington** [comment]
ISTR that page labels should behave properly here. To investigate for v2.3

**Comment by johnwhitington** [comment]
I have done some light testing here and can't find a bug. Can you supply an example file?
