### ISSUE TITLE
decompress prior squeeze can get more reduction  on most cases

### ISSUE THREAD

**Issue by maadjordan** [johnwhitington/cpdf-source#126]
I've noticed that if i ran -decompress command first on a file and then -squeeze the result is smaller size (either its fraction or minor) in most cases than just running -squeeze alone. sometimes is increase.

is it possible to add -decompress function to -squeeze routine as an option and can we predict if result will be reduction or not - if not to skip -decompress of that stream.

**Comment by johnwhitington** [comment]
Closing this as old, but feel free to re-open with an example file.
