### ISSUE TITLE
Feature request w/ patch: option to toggle bookmarks outline open/closed to certain depth

### ISSUE THREAD

**Issue by grr** [johnwhitington/cpdf-source#127]
Many times I open a pdf and all the levels of the bookmarks are open, so I have to manually toggle the folders closed to make them of any use. The pdf can be fixed by by calling `-list-bookmarks`, editing the output so the appropriate "open" strings are removed, then calling `-add-bookmarks` with the result, but that can be time consuming. I propose an option to make this simpler. `-toggle-bookmarks-depth 0` would not leave any bookmark level open, depth 1 would leave only the first level open, etc. Below is the implementation. Note this is the first time I've seen OCaml code, so it might not be perfect. The only time the levels were not correctly adjusted were when issue #123 was encountered.

    diff --git a/cpdfcommand.ml b/cpdfcommand.ml
    index ebf6ce4..5619488 100644
    --- a/cpdfcommand.ml
    +++ b/cpdfcommand.ml
    @@ -78,6 +78,7 @@ type op =
    | TwoUpStack
    | RemoveBookmarks
    | AddBookmarks of string
    +  | ToggleBookmarksDepth of int
    | AddText of string
    | AddRectangle
    | RemoveText
    @@ -183,6 +184,7 @@ let string_of_op = function
    | TwoUpStack -> "TwoUpStack"
    | RemoveBookmarks -> "RemoveBookmarks"
    | AddBookmarks _ -> "AddBookmarks"
    +  | ToggleBookmarksDepth _ -> "ToggleBookmarksDepth"
    | AddText _ -> "AddText"
    | AddRectangle -> "AddRectangle"
    | RemoveText -> "RemoveText"
    @@ -609,7 +611,7 @@ let banned banlist = function
    | Decrypt | Encrypt | CombinePages _ -> true (* Never allowed *)
    (* ISO says Noextract no longer relevent, due to accessibility concerns *)
    (*| ExtractText | ExtractImages | ExtractFontFile -> mem Pdfcrypt.NoExtract banlist*)
    -  | AddBookmarks _ | PadBefore | PadAfter | PadEvery _ | PadMultiple _
    +  | AddBookmarks _ | ToggleBookmarksDepth _ | PadBefore | PadAfter | PadEvery _ | PadMultiple _
    | Merge | Split | SplitOnBookmarks _ | RotateContents _ | Rotate _
    | Rotateby _ | Upright | VFlip | HFlip | SetPageLayout _
    | SetPageMode _ | HideToolbar _ | HideMenubar _ | HideWindowUI _
    @@ -1151,6 +1153,11 @@ let setopacity o =
    let setaddbookmarks s =
    setop (AddBookmarks s) ()
    
    +let settogglebookmarksdepth d =
    +  if d >= 0
    +    then setop (ToggleBookmarksDepth d) ()
    +    else error "invalid bookmark depth"
    +
    let setstampon f =
    setop (StampOn f) ();
    (* Due to an earlier bad decision (default position), we have this nasty hack *)
    @@ -1734,6 +1741,9 @@ and specs =
        ("-add-bookmarks",
        Arg.String setaddbookmarks,
        " Add bookmarks from the given file");
    +   ("-toggle-bookmarks-depth",
    +      Arg.Int settogglebookmarksdepth,
    +      " Toggle bookmarks open to given depth, close after");
        ("-presentation",
        Arg.Unit (setop Presentation),
        " Make a presentation");
    @@ -3404,7 +3414,7 @@ let go () =
            let pdf = get_single_pdf args.op true in
                let range = parse_pagespec pdf pagespec in
                Cpdf.output_page_info (get_single_pdf (Some PageInfo) true) range
    -      | _ -> error "list-bookmarks: bad command line"
    +      | _ -> error "page-info: bad command line"
        end
    | Some Metadata ->
        Cpdf.print_metadata (get_single_pdf (Some Metadata) true)
    @@ -3861,6 +3871,13 @@ let go () =
            (get_single_pdf args.op false))
    | Some RemoveBookmarks ->
        write_pdf false (Pdfmarks.remove_bookmarks (get_single_pdf args.op false))
    +  | Some (ToggleBookmarksDepth depth) ->
    +      let pdf = get_single_pdf args.op false in
    +      let marks = Pdfmarks.read_bookmarks pdf in
    +      let new_marks = map (fun m ->  {Pdfmarks.level = m.Pdfmarks.level; Pdfmarks.text = m.Pdfmarks.text;
    +          Pdfmarks.target = m.Pdfmarks.target;
    +          Pdfmarks.isopen = if (m.Pdfmarks.level < depth) then true else false}) marks in
    +      write_pdf false (Pdfmarks.add_bookmarks new_marks pdf)
    | Some TwoUp ->
        write_pdf false (Cpdf.twoup (get_single_pdf args.op false))
    | Some TwoUpStack ->

**Comment by johnwhitington** [comment]
Wish granted in forthcoming v2.3
