### ISSUE TITLE
"-no-copy" is not working as it should

### ISSUE THREAD

**Issue by fatonh** [johnwhitington/cpdf-source#131]
When I use the command `cpdf -encrypt 128bit admin user -no-copy in.pdf -o out.pdf` and then I check the status of the file `cpdf -info out.pdf` it says:

Encryption: 128bit
Permissions: No copy
Linearized: false

But when I open the PDF file I still can copy the content from pdf

**Comment by johnwhitington** [comment]
You can see that the flag has been set correctly -- it's in the output of -info, as you say.

What your PDF viewer chooses to do with that flag (including ignore it) is entirely up to it. What PDF viewer are you using?

**Comment by fatonh** [comment]
I did another test. It works fine if I open PDF file on chrome (I can not copy content). Issue is when I open on Preview (macOS sierra ).

Flag "-no-print" seems to work just fine also when I open on Preview (It prints blank page)

**Comment by johnwhitington** [comment]
Right, so there is nothing we can do about this. It’s just Preview’s behaviour....
