### ISSUE TITLE
squeeze fails with Unknown Error Initial file size is 0 bytes

### ISSUE THREAD

**Issue by iandi91** [johnwhitington/cpdf-source#132]
Hi, I'm trying to compress a PDF (size: 1.3 GB) but it fails with the above mentioned error message 😢 

> C:\cpdf>cpdf.exe -squeeze "file.pdf" -o "file_new.pdf
> cpdf encountered an error. Technical details follow:
> 
> Unknown error
> 
> Initial file size is 0 bytes

**Comment by johnwhitington** [comment]
Can you supply the file?

**Comment by iandi91** [comment]
Can you contact me at andreas@mymuesli.com to work out the details?

**Comment by johnwhitington** [comment]
Done.
