### ISSUE TITLE
inconsistent assumptions over interface Pdfutil : make[1]: *** [cpdf] Error 2

### ISSUE THREAD

**Issue by sebma** [johnwhitington/cpdf-source#133]
Hi,

Here is what make prints to the screen : 
```make
$ make
ocamlfind ocamlopt \
				-package camlpdf -linkpkg \
				        -g        -o cpdf \
				xmlm.cmx cpdfstrftime.cmx cpdf.cmx cpdfcommand.cmx cpdfcommandrun.cmx
File "_none_", line 1:
Error: Files cpdfstrftime.cmx
       and /Users/xxxxxxx/.opam/system/lib/camlpdf/camlpdf.cmxa
       make inconsistent assumptions over interface Pdfutil
make[1]: *** [cpdf] Error 2
make: *** [native-code] Error 2
```
Can you help me ?

**Comment by johnwhitington** [comment]
You need to run `make clean` first. The first command `make` is running is the linker, which means you have leftover .cmx files from some other version of cpdf in the cpdf directory.

Also, why are you using an opam-installed camlpdf? I thought the whole trouble was that you needed master versions of camlpdf and cpdf. In which case, you should install camlpdf directly through ocamlfind, surely?

**Comment by sebma** [comment]
@johnwhitington Thanks. I works now :-)

**Comment by sebma** [comment]
@johnwhitington Thanks. I works now :-)
