### ISSUE TITLE
cpdf and control file 

### ISSUE THREAD

**Issue by grylem** [johnwhitington/cpdf-source#134]
Make control.txt
-utf8
-set-keywords testkeywords
-set-title testtitle
-set-author testauthor
-set-subject testsubject
cpdf -control control.txt in.pdf -o out.pdf
only last line(testsubject) set to out.pdf

cpdf -set-keywords testkeywords -set-title testtitle -set-author testauthor
only testauthor in out.pdf
can I do something wrong?
tried it with AND but failed

**Comment by johnwhitington** [comment]
Please give the AND command line...

**Comment by grylem** [comment]
i tried like
for control.txt
-set-keywords testkeywords AND
-set-title testtitle AND
-set-author testauthor
whatever only last line

for command line 
cpdf -set-keywords testkeywords AND -set-title testtitle AND -set-author testauthor in.pdf -o out.pdf
cpdf: No input specified. Use -help for help.

**Comment by johnwhitington** [comment]
Put in.pdf before the first AND.

**Comment by grylem** [comment]
thanks a lot working for command line but what is the correct syntax for control.txt?

**Comment by johnwhitington** [comment]
Use -args not -control, as per the manual.

**Comment by grylem** [comment]
sorry, it's my fault i tried -args instead -control but forgot to add AND to control.txt
thanks again
