### ISSUE TITLE
Insert Image and Text Below Image

### ISSUE THREAD

**Issue by lavanyadeepak** [johnwhitington/cpdf-source#141]
I am looking to see if I can insert an image at the right top leaving a small margin and adding two to three lines of text below the image .

Is this possible?  Any example commandline options? 

I have tried a few options with the permutations from manual but it keeps overwriting these elements.

**Comment by johnwhitington** [comment]
You could prepare the file containing the image as a PDF file, then use -stamp-on or -stamp-under to put them together. Cpdf does not know how to insert images directly.
