### ISSUE TITLE
Manual Updating Requests

### ISSUE THREAD

**Issue by maadjordan** [johnwhitington/cpdf-source#147]
1- Elaborating combined commands like -squeeze :
As you are updating the manual can you add the equivalent of grouped command like -squeeze so not to repeat the sup-command (i think -clean is not required if -squeeze added ?).

2- Adding other unwritten functions to manual: ( I found several commands by reading source code).

 3- Can bookmark be copied from one pdf to another using "-list-bookmark" and "-add-bookmark" ?

**Comment by johnwhitington** [comment]
> 3- Can bookmark be copied from one pdf to another using "-list-bookmark" and "-add-bookmark" ?

Do you mean 'without'?

**Comment by maadjordan** [comment]
No  i meant that by using both commands (sequentially or combined) to transfer bookmarks from one file to another
