### ISSUE TITLE
adding and removing watermark

### ISSUE THREAD

**Issue by ff12345670** [johnwhitington/cpdf-source#169]
Hello,

i need to add a watermark to a pdf file using the -stamp-on option.

In a later time i need to remove that watermark from that same PDF file. How can i do that ?

**Comment by johnwhitington** [comment]
In the latest (not yet released) cpdf v2.3, which you would have to compile yourself, you can use -draft -remove-only to remove just one image. So if your watermark is just an image, that would work.

If your watermark is just text, you can use add-text and remove-text, to remove text previously added by cpdf.

But in the general case, no. Some future version of cpdf might have support for PDF layers, which would enabel this sort of thing.

Another option is to use -add-rectangle to overwrite the watermark. But this would rely on the watermarked region being just part of the page.
