### ISSUE TITLE
Supprt Unicode handling in file name

### ISSUE THREAD

**Issue by maadjordan** [johnwhitington/cpdf-source#171]
based on released v2.3 the unicode handling in file name still not working.

**Comment by johnwhitington** [comment]
Thanks. It looks like it was compiled under a too-early version of OCaml. I'll fix it this week.

**Comment by maadjordan** [comment]
also notice that compiled file of 2x size of v2.2

**Comment by johnwhitington** [comment]
It's the 64 bit build by default now, hence the size change.

**Comment by johnwhitington** [comment]
Please test http://www.coherentpdf.com/16thSeptember2019.zip for me. This has been compiled with the latest OCaml.

**Comment by maadjordan** [comment]
I can confirm that this build can handle Hebrew and Arabic lettering.. Thanks
