### ISSUE TITLE
producer field now always being set to cpdf

### ISSUE THREAD

**Issue by grr** [johnwhitington/cpdf-source#172]
previous versions of cpdf didn't modify the producer field, now any use of cpdf will cause the producer field to be set to "cpdf non-commercial use only. To buy: http://coherentpdf.com/", even when using `-set-producer`.  if this is intention, the manual should be updated to indicate this.

**Comment by johnwhitington** [comment]
Which binary did you download?

**Comment by grr** [comment]
https://github.com/coherentgraphics/cpdf-binaries/blob/master/OSX-Intel/cpdf

and then i tried to build cpdf using ocaml 4.08.1 and opam, but got the following error:
```ocamlfind ocamlopt -package camlpdf -c -annot -bin-annot -g -safe-string -w -3 cpdf.ml
File "cpdf.ml", line 976, characters 51-62:
976 |       let page = Pdfpage.pagenumber_of_target pdf ~fastrefnums target in
                                                         ^^^^^^^^^^^
Error: The function applied to this argument has type
         ?refnums:int list -> int
This argument cannot be applied with label ~fastrefnums```

**Comment by johnwhitington** [comment]
You need to match cpdf and camlpdf versions -- 2.3 with 2.3 or 2.2 with 2.2 etc.

**Comment by johnwhitington** [comment]
I just looked back through the git history, and it looks like this was introduced for v2.2, not the latest one (v2.3). So it's been there a few years.

I'll fix the documentation on the page community.coherentpdf.com to reflect this (and the fact that it prints a message when run)

**Comment by grr** [comment]
FYI, I just confirmed with the binaries for 2.2 and 2.2 patchlevel 1 downloaded from here:
https://github.com/coherentgraphics/cpdf-binaries/commits/master/OSX-Intel
and that was not introduced until 2.3.

**Comment by johnwhitington** [comment]
I've now updated the community website to reflect the change.
