### ISSUE TITLE
Win32  is no-op

### ISSUE THREAD

**Issue by AlanHK** [johnwhitington/cpdf-source#180]
I downloaded the current 2.3 release of the community release to my PC running WinXP SP3.
I extracted the Win32  cpdf and tried several commands .  e.g. 
cpdf -info file.pdf 
No output. Trying commands that should create PDF files, nothing happens. No errors, just nothing.
I tried the commercial demo with the same results.

I then tried the "Windows" cpdf, presumably 64 bit, on a PC running Win7 x64; that ran as expected.

Is the Win32 cpdf supposed to run on XP? If not, is there an older version that does?
 
Also, looking in the manual, there does not seem to be a "-h" option listing available commands . That would be helpful.

**Comment by johnwhitington** [comment]
Very interesting. I take it v2.2.1 works (that is 32bit too)?

**Comment by AlanHK** [comment]
Thanks. Where can I get 2.2.2 binaries? 
http://community.coherentpdf.com/ only has a link to the current version.

**Comment by johnwhitington** [comment]
Click through to github, then select the ‘tag’ v2.2.1 from the drop down menu in the top left. If you then ask for a zip download, it should be from that tagged version.

**Comment by johnwhitington** [comment]
https://github.com/coherentgraphics/cpdf-binaries

Starting here

**Comment by AlanHK** [comment]
OK, version 2.2 (and also 2.1) work on WinXP.

**Comment by johnwhitington** [comment]
Thanks. I have talked to producers of the tools we use for compilation, and they confirm that new executables, built today, cannot support Windows XP. I will update the documentation.

So, I'm afraid you are stuck with v2.2.1, unless you are a paying customer.
