### ISSUE TITLE
Setting page labels with an input range

### ISSUE THREAD

**Issue by dwightkelly** [johnwhitington/cpdf-source#184]
If an input range is specified the page label counter resets to starting value.

```
cpdf -add-page-labels in.pdf odd -label-style DecimalArabic -label-startval 100 -o out.pdf
```

will label every odd page with '100' instead of expected '100', '101', '102', '103', etc. on the odd pages only.

**Comment by johnwhitington** [comment]
Your expectation was that this command would leave the page labels on even pages alone, and alter the odd pages to have labels ‘100’ for page 1, ‘101’ for page 3, ‘102’ for page 5 etc? Is that right?

**Comment by dwightkelly** [comment]
Correct. Same behavior as an input range of 4-9 only changes those 6 pages.

**Comment by johnwhitington** [comment]
I have looked at the code, and what happens is that the range is split into one or more contiguous ranges, and the `-label-startval` is the same for each one.

The manual does not specify the behaviour, so we are free to change cpdf to treat `-label-startval` differently when there are multiple ranges, so long as we document it.

If you are an existing or potential commercial customer, please let me know and I can fix this in the next couple of days.

If you are using the non-commercial version, I'm afraid this will have to wait for the next version. I have tagged this bug accordingly.

**Comment by dwightkelly** [comment]
We are evaluating cpdf prior to purchase.

**Comment by johnwhitington** [comment]
Ok, I will provide a fix for you tomorrow morning.

Will you build from source, or would you like an executable? If an executable, please specify platform.

**Comment by dwightkelly** [comment]
I’ve not built from your source but can try. Thank you.

**Comment by johnwhitington** [comment]
Consider a ten-page document with no existing labels:

Without `-label-startval`, each range starts at 1:

```
cpdf -add-page-labels out.pdf 2-4,6-8
     -label-style LowercaseRoman
     -o labels.pdf
```

So we get

1, i, ii, iii, 5, i, ii, iii, 9, 10

With `-label-startval`, each range starts at given values

```
cpdf -add-page-labels out.pdf 2-4,6-8
     -label-startval 5
     -label-style LowercaseRoman
     -o labels.pdf
```

so we get:

1, v, vi, vii, 5, v, vi, vii, 9, 10

My plan is to add a new option `-labels-progress` which, when in effect, would assign a `startval` of 5 for the range `2-4`, and a `startval` of 8 for the range `6-8` so with this command:

```
cpdf -add-page-labels out.pdf 2-4,6-8
     -label-startval 5
     -labels-progress 
     -label-style LowercaseRoman
     -o labels.pdf
```

so we get:

1, v, i, vii, 5, viii, ix, x, 9, 10

This should work for the original problem with `odd`, since `odd` expands to the range `1, 3, 5...` i.e many length 1 ranges.

**Comment by johnwhitington** [comment]
This had now been implemented in trunk. Add `-labels-progress` as described in the preceding comments.

To compile from source you must use tip-of-trunk camlpdf and tip-of-trunk cpdf.

Here is an OS X Binary: 

http://coherentpdf.com/25thJanuary2020.zip

(it's not code-signed or notarized, so you may need to use system preferences to get it out of quarantine if you're on catalina)

Obviously, if you choose to purchase, I can provide any other binaries you need.

Let me know how you get on.

**Comment by dwightkelly** [comment]
Thank you. I will purchase a license on Monday regardless - just for the excellent service.

**Comment by schmidhauser** [comment]
Sorry for jumping in, but I was wondering whether you’ve have made any further changes.

As I understand your earlier comments, the command

```
cpdf -add-page-labels in.pdf odd
	 -label-startval 5
	 -labels-progress
	 -label-style LowercaseRoman
	 -o out.pdf
```

should produce the following labels:

	v, 2, vi, 4, vii, 6, viii, 8, ix, 10

Yet if I use the binary you posted above (v2.4 [devel, 24th January 2020]), I get the following:

	v, 2, vi, 4, viii, 6, x, 8, xii, 10

I’m not a commercial customer. I just wanted to note this in case it got overlooked.

**Comment by johnwhitington** [comment]
Thanks. Fixed here:

https://github.com/johnwhitington/cpdf-source/commit/ca49e9d25e01e5cfaadccc47bb68e470802b0808
