### ISSUE TITLE
Add bookmarks not working in the version 2.3

### ISSUE THREAD

**Issue by arthurmolina** [johnwhitington/cpdf-source#192]
The same command line:
`cpdf` -add-bookmarks bookmarks.txt final_file.pdf -o final_file.pdf

when I use the version 2.2 I get no response (status code 0) but it does the job.

when I use the version 2.3 I get this response:
```
For non-commercial use only
To purchase a license visit http://www.coherentpdf.com/

Bad bookmark file (syntax) at line 0 (error was Cpdf.SoftError("Bad bookmark file (References non-existant pages or is malformed)"))
```

**Comment by johnwhitington** [comment]
The bookmark format has been expanded in v2.3, but should be backward compatible. Can you send the bookmark file and, if possible, the PDF file, please. If you can't send the PDF file, please let me know how many pages it has.

**Comment by johnwhitington** [comment]
Closing, since no repro case

**Comment by johnwhitington** [comment]
Closing, since no repro case
