### ISSUE TITLE
Cannot compile last git

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [johnwhitington/cpdf-source#197]
Hello,

I got this when "make"

ocamlfind ocamlopt -package camlpdf -c -annot -bin-annot -g -safe-string -w -3 cpdf.ml
File "cpdf.ml", line 587, characters 31-54:
Error: Unbound value string_replace_all_lazy
make[1]: *** [OCamlMakefile:1076: cpdf.cmx] Error 2
make[1]: Leaving directory '/home/src/cpdf'
make: *** [OCamlMakefile:777: native-code] Error 2

Any clue? thanks!

**Comment by johnwhitington** [comment]
Please don't use trunk; it's unstable.

But the root problem here is that you need to pick the same tag version for both CamlPDF and CPDF: e.g v2.3.1 for the latest version. If the version numbers don't match it won't build.

Let me know how you get on...

**Comment by ROBERT-MCDOWELL** [comment]
Hi John,
if I understand I have to clone the CamlPDF source too and install it?
I did but get also a compile error:

ocamlc -c -cc "cc" -ccopt "-fPIC  \
                        -DPIC   \
                            -o ba.o " ba.c
ba.c:73:3: error: ‘caml_ba_finalize’ undeclared here (not in a function); did you mean ‘caml_initialize’?
   73 |   caml_ba_finalize,
      |   ^~~~~~~~~~~~~~~~
      |   caml_initialize
ba.c:74:3: error: ‘caml_ba_compare’ undeclared here (not in a function); did you mean ‘caml_ba_ops’?
   74 |   caml_ba_compare,
      |   ^~~~~~~~~~~~~~~
      |   caml_ba_ops
ba.c:75:3: error: ‘caml_ba_hash’ undeclared here (not in a function); did you mean ‘caml_ba_ops’?
   75 |   caml_ba_hash,
      |   ^~~~~~~~~~~~
      |   caml_ba_ops
ba.c:76:3: error: ‘caml_ba_serialize’ undeclared here (not in a function); did you mean ‘caml_initialize’?
   76 |   caml_ba_serialize,
      |   ^~~~~~~~~~~~~~~~~
      |   caml_initialize
ba.c:77:3: error: ‘caml_ba_deserialize’ undeclared here (not in a function)
   77 |   caml_ba_deserialize,
      |   ^~~~~~~~~~~~~~~~~~~
ba.c:79:3: error: ‘custom_fixed_length_default’ undeclared here (not in a function); did you mean ‘custom_finalize_default’?
   79 |   custom_fixed_length_default
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~
      |   custom_finalize_default
ba.c:79:3: warning: excess elements in struct initializer
ba.c:79:3: note: (near initialization for ‘caml_ba_ops’)
ba.c: In function ‘caml_ba_alloc’:
ba.c:106:11: warning: implicit declaration of function ‘caml_umul_overflow’ [-Wimplicit-function-declaration]
  106 |       if (caml_umul_overflow(num_elts, dimcopy[i], &num_elts))
      |           ^~~~~~~~~~~~~~~~~~
ba.c:118:9: warning: implicit declaration of function ‘caml_alloc_custom_mem’; did you mean ‘caml_alloc_custom’? [-Wimplicit-function-declaration]
  118 |   res = caml_alloc_custom_mem(&caml_ba_ops, asize, size);
      |         ^~~~~~~~~~~~~~~~~~~~~
      |         caml_alloc_custom
ba.c: In function ‘caml_ba_hash’:
ba.c:254:3: error: unknown type name ‘uint32_t’; did you mean ‘u_int32_t’?
  254 |   uint32_t h, w;
      |   ^~~~~~~~
      |   u_int32_t
ba.c:294:5: error: unknown type name ‘uint32_t’; did you mean ‘u_int32_t’?
  294 |     uint32_t * p = b->data;
      |     ^~~~~~~~
      |     u_int32_t
ba.c: In function ‘caml_ba_uint8_get32’:
ba.c:650:3: error: unknown type name ‘uint32_t’; did you mean ‘u_int32_t’?
  650 |   uint32_t res;
      |   ^~~~~~~~
      |   u_int32_t
ba.c: In function ‘caml_ba_uint8_get64’:
ba.c:669:3: error: unknown type name ‘uint64_t’; did you mean ‘u_int64_t’?
  669 |   uint64_t res;
      |   ^~~~~~~~
      |   u_int64_t
ba.c:688:10: error: ‘uint64_t’ undeclared (first use in this function); did you mean ‘u_int64_t’?
  688 |   res = (uint64_t) b8 << 56 | (uint64_t) b7 << 48
      |          ^~~~~~~~
      |          u_int64_t
ba.c:688:10: note: each undeclared identifier is reported only once for each function it appears in
ba.c:688:19: error: expected ‘;’ before ‘b8’
  688 |   res = (uint64_t) b8 << 56 | (uint64_t) b7 << 48
      |                   ^~~
      |                   ;
make[1]: *** [OCamlMakefile:1132: ba.o] Error 2
make[1]: Leaving directory '/home/src/camlpdf'
make: *** [OCamlMakefile:792: byte-code-library] Error 2

**Comment by ROBERT-MCDOWELL** [comment]
btw my environment:
Fedora Linux 64bits with custom kernel 5.7.0

**Comment by johnwhitington** [comment]
Again, it looks like you're trying to build trunk. You would need to change to tag v2.3.1 first.

If you just need a binary, there are available here: https://github.com/coherentgraphics/cpdf-binaries

**Comment by ROBERT-MCDOWELL** [comment]
ooops, sorry I don't have the habit to specify the branch when I clone a repository.
everything is fine now on one node, but another node complain about ocamlfind.conf
make[1]: *** Deleting file '._d/cpdfstrftime.d'
ocamlfind ocamldep xmlm.ml > ._d/xmlm.d
ocamlfind: Config file not found - neither /usr/etc/findlib.conf nor the directory /usr/etc/findlib.conf.d
make[1]: *** Deleting file '._d/xmlm.d'
ocamlfind ocamlc -package camlpdf -c -annot -bin-annot xmlm.mli
ocamlfind: Config file not found - neither /usr/etc/findlib.conf nor the directory /usr/etc/findlib.conf.d
make[1]: *** [OCamlMakefile:1056: xmlm.cmi] Error 2
make[1]: Leaving directory '/home/src/cpdf-source'
make: *** [OCamlMakefile:777: native-code] Error 2

I'm not familiar with ocaml and don't know how to solve it.

**Comment by johnwhitington** [comment]
Have you installed Ocamlfind from here: http://projects.camlcity.org/projects/findlib.html ?

It looks from your error that it is installed but perhaps wrongly, since it doesn't seem to be able to locate its own config file! Try reinstalling...

**Comment by ROBERT-MCDOWELL** [comment]
ok I reinstalled all ocaml* related package on my nodes, after some glitches now when i 'make' in camlpdf it says
ocamlfind: Not supported in your configuration: ocamldoc
search on the net to investigate but didn't find a solution ye :(

**Comment by ROBERT-MCDOWELL** [comment]
weird, ocaml-ocmldoc Fedora package is installed though

**Comment by johnwhitington** [comment]
If you don't need the docs (you probably don't, it's not the PDF manual), just type "make nc" to avoid the "docs" make target being run. You should find "cpdf" is built.

**Comment by ROBERT-MCDOWELL** [comment]
Ok got it!, Geeez, ocaml is version conflict allergic :D...
dunno how but ocaml libs and package were very messy. all are clean now, 
CPDF is a very good piece of software, fantastic job you did John!
I use it for now just to attach files with a pdf built with wkhtmltopdf.
works great and fast. Thank you!
