### ISSUE TITLE
-pages options cant't redirect output to a file

### ISSUE THREAD

**Issue by drazde** [johnwhitington/cpdf-source#201]
Hi, 
I would like use `cpdf` in my windows serviece. 
When I try to use it with `-pages` I can't get the number because the programs runs in windows services cant't write on standard output.

Could you write all the info about a pdf directly in a text file (not only on standard output)?
Thanks Marco

**Comment by johnwhitington** [comment]
It seems there are suggested workarounds for wrapping up tools which produce output into a service.

For example, see the 'update' section of "Solution 2" on this page:

https://www.codeproject.com/Questions/164580/Windows-Services-and-stdout-does-not-seem-to-work

If there is absolutely no way you can get a workaround to work, we could add it as functionality in cpdf (for a paying customer), of course. But surely one of the workarounds will work?

**Comment by drazde** [comment]
You could be close this issue I use another tool
