### ISSUE TITLE
Command 'cpdf' not found

### ISSUE THREAD

**Issue by keranterol** [johnwhitington/cpdf-source#202]
Hello!

I installed cpf from Opam, however, when try to run a command with cpdf such as `cpdf -version` I receive a message that the Command 'cpdf' wasn't found as seen bellow:

> $ cpdf --help
> 
> Command 'cpdf' not found, did you mean:
> 
>   command 'xpdf' from deb xpdf
>  command 'qpdf' from deb qpdf
>   command 'cpif' from deb noweb
> 
> Try: sudo apt install <deb name>
> 
> $ opam install cpdf
> [NOTE] Package cpdf is already installed (current version is 2.3).
> $ cpdf -help
> 
> Command 'cpdf' not found, did you mean:
> 
>   command 'xpdf' from deb xpdf
>   command 'qpdf' from deb qpdf
>   command 'cpif' from deb noweb
> 
> Try: sudo apt install <deb name>

Before installing from opam, I was able to install the OCaml compiler but not the other dependences. Is there anything I've done wrongly? I'm new to linux and programming, I'm learning as I need to do something.

**Comment by johnwhitington** [comment]
Hi!

You can install the binary directly, from here:

https://github.com/coherentgraphics/cpdf-binaries


I can look into the issue of why the opam package is not installed the cpdf binary where you can find it, but not today I'm afraid.

**Comment by keranterol** [comment]
Thank you!
After downloading, I followed these steps on terminal:
`sudo chmod +x ./cpdf`
`sudo ./cpdf`

It printed the info about the license, however it didn't solve the issue. Should've I moved to a specific directory before? 

I don't know if it will help, but after that, I ran `opam show cpdf` and the terminal printed:
> <><> cpdf: information on all versions ><><><><><><><><><><><><><><><><><><><><>
> name                   cpdf
> all-installed-versions 2.3 [default]
> all-versions           1.7  2.1.1  2.2.1  2.3
> 
> <><> Version-specific details <><><><><><><><><><><><><><><><><><><><><><><><><>
> version       2.3
> repository    default
> url.src:      "https://github.com/johnwhitington/cpdf-source/archive/v2.3.zip"
> url.checksum: "md5=cf90567bf5f114917abfc563262a845a"
> homepage:     "http://github.com/johnwhitington/cpdf-source"
> bug-reports:  "http://github.com/johnwhitington/cpdf-source/issues"
> dev-repo:     "git://github.com/johnwhitington/cpdf-source"
> authors:      "John Whitington"
> maintainer:   "contact@coherentgraphics.co.uk"
> depends:      "ocaml" {>= "4.02.0"} "ocamlfind" {build} "camlpdf" {= "2.3"}
> synopsis      High-level pdf tools based on CamlPDF

**Comment by johnwhitington** [comment]
Ok, so you have the cpdf binary working.

If you want to, you can put it somewhere on your default path, for example in /usr/local/bin. Then you can type 'cpdf' anywhere, without needing cpdf to be in the current directory.

You seem to be confusing two things: the cpdf library, which OPAM is installing for you, and `cpdf` the command-line tool, which is what you have just downloaded as a binary.

**Comment by keranterol** [comment]
Oh, I see it.

I moved as you said and it worked, thank you for your time and patience!

**Comment by johnwhitington** [comment]
Great.
