### ISSUE TITLE
Bookmarks are not scaled with content

### ISSUE THREAD

**Issue by ldr709** [johnwhitington/cpdf-source#203]
When using `cpdf -scale-page` to enlarge a pdf document, the bookmarks no longer point to what they are supposed to. Their coordinates remain constant instead of being scaled so that they continue to point to the same relative location. That is, `cpdf -list-bookmarks` gives the same output for both the unscaled and scaled pdfs, but the coordinates ought to have been scaled.

**Comment by johnwhitington** [comment]
This should work fine in the latest version. What is the output of `cpdf -version`?

**Comment by ldr709** [comment]
```
$ cpdf -version
cpdf Version 2.3 (patchlevel 1, 11th December 2019)
```

**Comment by johnwhitington** [comment]
Thanks. Odd. Can you supply an example input file? If it's private you can send it to john at coherentgraphics dot co do t uk.

**Comment by ldr709** [comment]
Here's an example input file, and the result I get from running `cpdf -scale-page "2 2" example.pdf -o example-scaled.pdf`.
In `example.pdf` the bookmarks correctly send you to the section headings, but in `example-scaled.pdf` they do not. `cpdf -list-bookmarks` is identical for both.
```
$ cpdf -version
cpdf Version 2.4 (devel, 6th May 2020)
```

[example.pdf](https://github.com/johnwhitington/cpdf-source/files/5143920/example.pdf)
[example-scaled.pdf](https://github.com/johnwhitington/cpdf-source/files/5143921/example-scaled.pdf)

**Comment by johnwhitington** [comment]
I can confirm. Cpdf knows how to scale the page and its annotations, but seems not to scale the "actions" from the document outline (bookmarks).

I will need to look further to see if this is supposed to be there (and it is not triggering), or if we never implemented it.

Are you a commercial customer? If so, I can fix this next week. If not, it will have to go on the pile for the next release, I'm afraid.

**Comment by ldr709** [comment]
No, I'm just a non-commercial user. I was experimenting with using `cpdf` as part of the build process for an academic paper and happened to notice the bug. I have no urgent need for it to be fixed—I just thought that you would like to know about it.

Thank you for making a really useful pdf editing tool, and for making it available for non-commercial use.

**Comment by johnwhitington** [comment]
I have now implemented code to scale bookmark destinations and other annotation destinations. It will be in the upcoming v2.4.
