### ISSUE TITLE
Feature Request - Reverse page order

### ISSUE THREAD

**Issue by maadjordan** [johnwhitington/cpdf-source#208]
Is it possible to add possibility to reverse the page order of pdf files partially or complete.

Currently i use qpdf to fulfill this task

**Comment by johnwhitington** [comment]
Cpdf allows reverse page ranges e.g 6-3, or end-1.

**Comment by maadjordan** [comment]
It was not clear in the manual but I used 

cpdf in.pdf end-1 -o out.pdf

and it worked
