### ISSUE TITLE
Rotate only selected pages in a pdf

### ISSUE THREAD

**Issue by soubhikchatterjee** [johnwhitington/cpdf-source#212]
When i run the following command, it rotates ALL pages in the pdf.
`cpdf -rotate 90 in.pdf -o out.pdf`

Is there anyway, i can rotate just the pages 2 and 4 in the above pdf file?

**Comment by johnwhitington** [comment]
Hi,

Using ranges, which follow the input name:

cpdf -rotate 90 in.pdf 2,4 -o out.pdf

Thanks,

John

> On 23 Feb 2021, at 03:40, Soubhik Chatterjee <notifications@github.com> wrote:
> 
> 
> When i run the following command, it rotates ALL pages in the pdf.
> cpdf -rotate 90 in.pdf -o out.pdf
> 
> Is there anyway, i can rotate just the pages 2 and 4 in the above pdf file?
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

-- 
John Whitington
Director, Coherent Graphics Ltd
