### ISSUE TITLE
preserve OCGs when merging pages

### ISSUE THREAD

**Issue by dwightkelly** [johnwhitington/cpdf-source#217]
If the input PDF files have OCGs (layers), when merged with CPDF the inactive layers become visible. This is because CPDF doesn't merge the OCG definitions from input PDFs into output PDF.

**Comment by johnwhitington** [comment]
Already implemented in the developmemt version, I believe. Let me know what platform you’re using, and I can provide an executable...

**Comment by dwightkelly** [comment]
Linux x64

**Comment by johnwhitington** [comment]
Please try https://coherentpdf.com/tmp/27thApril2021.tar.bz2

Let me know if you find any problems -- this is new code.

**Comment by dwightkelly** [comment]
The OCG (layers) definitions are retained; however, the page elements are 'flattened' after merging. We need the elements to remain on the layers that they were on in the original PDFs. 

For example, if I call CPDF with this command-line:
cpdf -merge 8_5x14-DPF.pdf 1 8_5x14-Half.pdf 1  -o out.pdf

The layers "Guides/DO NOT PRINT" and "Your Art Here" are preserved in the output file; however, the elements are no longer assigned to those layers.

Original file
![Screen Shot 2021-05-03 at 12 27 56 PM](https://user-images.githubusercontent.com/160460/116904053-393f4e80-ac0b-11eb-844d-aea46211b010.png)
![Screen Shot 2021-05-03 at 12 28 07 PM](https://user-images.githubusercontent.com/160460/116904058-3a707b80-ac0b-11eb-8ede-03966eeecc12.png)

Merged file
![Screen Shot 2021-05-03 at 12 32 37 PM](https://user-images.githubusercontent.com/160460/116904451-b23ea600-ac0b-11eb-9325-69d93801c2c9.png)

Input PDFs
[8_5x14-DPF.pdf](https://github.com/johnwhitington/cpdf-source/files/6416138/8_5x14-DPF.pdf)
[8_5x14-Half.pdf](https://github.com/johnwhitington/cpdf-source/files/6416182/8_5x14-Half.pdf)

**Comment by johnwhitington** [comment]
Can you try `cpdf -ocg-coalesce-on-name out.pdf -o out2.pdf` and see what that gets you?

If no luck, I'll have to get back into this fully, which will mean blocking out a day. A good chance to document the undocumented OCG functionality though.

**Comment by dwightkelly** [comment]
I'm merging 2 documents and get this error message.
```
Operation OCGCoalesce already specified, so cannot specify operation Merge.
Use AND from Chapter 1 of the manual to chain commands together.
```
so I tried the command 
**cpdf -merge 8_5x14-DPF.pdf 1 8_5x14-DPF.pdf 2 AND -ocg-coalesce-on-name -o out_1.pdf**
 and it worked. I then tried merging pages from 2 different PDF files 
**cpdf -merge 8_5x14-DPF.pdf 1 8_5x14-Half.pdf 1 AND -ocg-coalesce-on-name -o out_3.pdf**
and it failed to retain elements on the layers defined in original PDFs.

**Comment by johnwhitington** [comment]
It looks like I commented out the new ocg merging stuff when making a release recently, just in case it wasn't ready yet. I've put it back in, and running with debug on we see:

1. merge the files:

```
$ cpdf 8_5x14-DPF.pdf 1 8_5x14-Half.pdf 1 -o merged.pdf
```

2. Check both sets of OCGs have been preserved:

```
$ cpdf -ocg-list merged.pdf
Your Art Here
Guides/DO NOT PRINT
Your Art Here
Guides/DO NOT PRINT
```

3. Coalesce them on names:

```
$ cpdf -ocg-coalesce-on-name merged.pdf -o out.pdf
54 = Your Art Here
26 = Guides/DO NOT PRINT
6 = Your Art Here
5 = Guides/DO NOT PRINT

Changes are:
5 -> 26
6 -> 54
```

I have attached the result `out.pdf`. Is it correct?

[out.pdf](https://github.com/johnwhitington/cpdf-source/files/6427697/out.pdf)

**Comment by dwightkelly** [comment]
yes, that's correct.

**Comment by johnwhitington** [comment]
Please try https://coherentpdf.com/tmp/5thMay2021.tar.bz2

**Comment by johnwhitington** [comment]
Did you have a chance to try this? I want to include it in v2.4 which is out soon, so confirmation it works for you would be great.

**Comment by dwightkelly** [comment]
yes, it is producing the correct output. Thank you
