### ISSUE TITLE
wrong source?

### ISSUE THREAD

**Issue by hubutui** [johnwhitington/cpdf-source#219]
Hey, I download the latest release source tarball from [here](https://github.com/johnwhitington/cpdf-source/archive/refs/tags/v2.4.tar.gz), and extract the source tree, and got: `cpdf-source-2.3.1`, but we expect `cpdf-source-2.4`. Could you check it out?

**Comment by johnwhitington** [comment]
I just tried it, and got 2.4. Can you try again?
