### ISSUE TITLE
Add printer's marks to a PDF

### ISSUE THREAD

**Issue by johnwhitington** [johnwhitington/cpdf-source#22]

**Comment by lucasbraum** [comment]
Any news on that? It would be awesome to have it :D

**Comment by johnwhitington** [comment]
-trim-marks added for forthcoming v2.3. Also -show-boxes to visually display positions of all the boxes for debug.

**Comment by kadarmarton** [comment]
There is a minor bug in the -trim-marks logic, in line:

https://github.com/johnwhitington/cpdf-source/blob/a42886db038be2e71411d66f434e3157c4b55bb3/cpdfpage.ml#L1035

The third argument, instead of `tminy -. allowance`, should be `tminx -. allowance`
