### ISSUE TITLE
Using merge-add-bookmarks-use-titles does not appear to insert bookmarks for these files.

### ISSUE THREAD

**Issue by jonnywilliamson** [johnwhitington/cpdf-source#222]
Hi John,

I've been playing around all afternoon with some test PDFs. I want to merge them and have a bookmark for each file added. When it came to the attached files below, I just couldn't get the merged file to include any bookmarks, yet using the the same command on other files was no issue.

I have tried the following:

`cpdf -merge -merge-add-bookmarks-use-titles 1.pdf 2.pdf -o final.pdf`
`cpdf -merge-add-bookmarks-use-titles 1.pdf 2.pdf -o final.pdf`
`cpdf -merge-add-bookmarks-use-titles -i 1.pdf -i 2.pdf -o final.pdf`

Running `-info` on the files show that they do have a title:

```
% cpdf -info 2.pdf
For non-commercial use only
To purchase a license visit http://www.coherentpdf.com/

Encryption: Not encrypted
Permissions:
Linearized: false
Version: 1.4
Pages: 5
Title: Aerodromes
Author: Lufthansa Systems FlightNav
Subject: none
Keywords:
Creator:
Producer: iText 2.1.6 by 1T3XT
Created: D:20210829150940Z
Modified: D:20210829150940Z
Trapped: False
```

Am I missing something or are these just funny (weird) pdfs?

Thank you.

[1.pdf](https://github.com/johnwhitington/cpdf-source/files/7072922/1.pdf)
[2.pdf](https://github.com/johnwhitington/cpdf-source/files/7072923/2.pdf)

**Comment by johnwhitington** [comment]
Try

```
cpdf 1.pdf 2.pdf -merge-add-bookmarks -merge-add-bookmarks-use-titles -o out.pdf
```

(-merge-add-bookmarks-use-titles is a suboption to -merge-add-bookmarks. Perhaps that is not clear from the documentation?)

**Comment by jonnywilliamson** [comment]
Oh wow. That worked first time.

Apart from being embarrassing, I don't consider myself a complete beginner when it comes to the command line at all. 

I feel very comfortable there, but I did *not* appreciate that `-merge-add-bookmarks-use-titles` was a suboption and needed to be used in conjunction with `-merge-add-bookmarks`.

Thank you for the reply that's a great help.

**Comment by jonnywilliamson** [comment]
Ok I just checked because it was bothering me and yes, I have files here that when I run only

`cpdf 1.pdf 2.pdf -merge-add-bookmarks-use-titles -o out.pdf`, and leave out the  `-merge-add-bookmarks` it WILL add the titles into the bookmarks.

Yet the above original 2 files attached in the first post do NOT work.

I am happy to send you these 2 other pdfs (200K each) that this is working for if you have any interest in it, but I would prefer not to publish them publically here, would like to send privately please.

If it's something you have any interest in looking into, please let me know.

Thank you again.

**Comment by johnwhitington** [comment]
You're not the first person to make this mistake, which is why I'm going to have another look at the documentation.

You can send the other two PDFs to john at coherentgraphics dot co dot uk, and I will work out what is happening.

**Comment by jonnywilliamson** [comment]
Thank you email sent.
