### ISSUE TITLE
Issue with -topright command

### ISSUE THREAD

**Issue by johseb** [johnwhitington/cpdf-source#225]
I'm trying to scale down the content of a document and move it to the top corner of the page (left top corner for odd pages and right top corner for even pages).

-topleft command applied to the odd pages works as expected; full command is:
`cpdf -scale-contents 0.80 -topleft 5 in.pdf odd -o out.pdf`

-topright command on the other hand seems to honor the vertical positioning but ignore the horizontal one.
The content is always moved to the right border with no margin regardless the measure in pts specified for the command.
Full command used:
`cpdf -scale-contents 0.80 -topright 5 in.pdf even -o out.pdf`

cpdf Version 2.4 (21st June 2021) on Mac OSX.

**Comment by johnwhitington** [comment]
Could you supply an example file? If it can't be attached here publicly, it can be sent privately to john at coherentgraphics dot co dot uk.

**Comment by johseb** [comment]
Here is a file I was trying to process:
[test_file.pdf](https://github.com/johnwhitington/cpdf-source/files/7583878/test_file.pdf)

(Notice that I duplicated the first page because the picture extends to the entire page and makes it easier to judge the positioning of the pages).

On a side note: the file contains a few annotations and they're not scaled and moved along with the content. I think that's by design (and I can remove them before processing the file) but on occasions it would be useful to have the annotations scaled.

**Comment by johnwhitington** [comment]
This turns out to be a typo in the code. The following:

```
      let tx, ty =
        let open Cpdfposition in
        match position with
        | Top t -> 0., -.t
        | TopLeft t -> t, -.t
        | TopRight t -> 0., -.t
        | Left t -> t, 0.
        | BottomLeft t -> t, t
        | Bottom t -> 0., t
        | BottomRight t -> -.t, -.t
        | Right t -> -.t, 0.
```

should read:

```
      let tx, ty =
        let open Cpdfposition in
        match position with
        | Top t -> 0., -.t
        | TopLeft t -> t, -.t
        | TopRight t -> 0., -.t
        | Left t -> t, 0.
        | BottomLeft t -> t, t
        | Bottom t -> 0., t
        | BottomRight t -> -.t, -.t
        | Right t -> -.t, 0.
```

(Both `TopRight` and `BottomRight` were wrong).

Please let me know which platform you're using, and a way to reach you privately, and I can supply a new executable.

The annotations should be scaled and moved, but I'll look into that once we have this more urgent problem fixed.

**Comment by johseb** [comment]
Thanks.
Just sent you a mail.
