### ISSUE TITLE
Round trip image data (e.g JPEGs) through external processor.

### ISSUE THREAD

**Issue by johnwhitington** [johnwhitington/cpdf-source#244]

**Comment by johnwhitington** [comment]
What is the best interface for this?

**Comment by necros2k7** [comment]
I think you can use :
https://exiftool.org/
https://github.com/fhanau/Efficient-Compression-Tool
https://github.com/mozilla/mozjpeg (jpegtran utility inside release file)

**Comment by necros2k7** [comment]
https://github.com/tjko/jpegoptim
