### ISSUE TITLE
How to split the pdf path by bookmarks and auto output each bookmark name?

### ISSUE THREAD

**Issue by lyscop** [johnwhitington/cpdf-source#246]
I try to use this `cpdf.exe -split-bookmarks 1 C:\Users\Administrator\Desktop\New.pdf`

It gives an error, may it not support the path of the file.

Then I put the pdf file in the cpdf.exe folder and use `cpdf.exe -split-bookmarks 1 New.pdf -o xxxx.pdf`

It seems must set the name of each file but not the bookmarks name.

**Comment by johnwhitington** [comment]
There is no command called "-bookmarks". There is "-list-bookmarks", for example, and some others.

Please try again. If you still have a problem, please update this bug report with exactly the commands and output you see.

**Comment by lyscop** [comment]
Sorry for the writing error. Updated.

**Comment by johnwhitington** [comment]
There are three locations here:

a) The folder you are in when you execute the command
b) The folder cpdf.exe is in
c) The folder your PDF file is in

1. cpdf.exe must be in the folder you are executing the command in, or in a standard installed location such as C:\Program Files\
2. You are giving the full path to the PDF file.
3. The output files from the split will go in the folder you are executing the command in

Please show me the actual error message. Only then can I help you.

**Comment by lyscop** [comment]
Yeah, it done by the file path `cpdf.exe -split-bookmarks 0 C:\Users\Administrator\Desktop\1.pdf -o C:\Users\Administrator\Desktop@N.pdf` 

But not the bookmark name, could name the after splitting file as the bookmark?

**Comment by johnwhitington** [comment]
Can you send the PDF for me to look at? If it's private, you can email it to john at coherentgraphics.co.uk instead of uploading it here.

**Comment by lyscop** [comment]
[New.pdf](https://github.com/johnwhitington/cpdf-source/files/8402439/New.pdf)

Use the above command line to split by the bookmarks, and the result is 1.pdf 2.pdf 3.pdf 4.pdf

**Comment by johnwhitington** [comment]
So you need @B, not @N, per the manual. Where did you see @N? Maybe there is a mistake in the documentation somewhere?

**Comment by johnwhitington** [comment]
Sorry, Github messed up the formatting. @B is what is required.

**Comment by lyscop** [comment]
Thank you so much, it works well now.

[https://www.coherentpdf.com/cpdfmanual/cpdfmanualli1.html#x2-3000](https://www.coherentpdf.com/cpdfmanual/cpdfmanualli1.html#x2-3000)

[https://www.coherentpdf.com/usage-examples.html](https://www.coherentpdf.com/usage-examples.html)

**Comment by johnwhitington** [comment]
Thanks for the links. I'll fix these in a moment.

**Comment by lyscop** [comment]
> Thanks for the links. I'll fix these in a moment.

Sorry for trouble you again. 

I find it doesn't support splitting it by the bookmark in Chinese.

```
cpdf.exe -split-bookmarks 0 "C:\Users\Administrator\Desktop\New1.pdf" -o C:\Users\Administrator\Desktop\@B.pdf
For non-commercial use only
To purchase a license visit http://www.coherentpdf.com/

C:\Users\Administrator\Desktop\b.pdf: No such file or directory
```

**Comment by johnwhitington** [comment]
At the moment, cpdf treats bookmarks names as ASCII, and removes any bytes above 127 or below 32, and any of these:

'/' | '?' | '<' | '>' | '\\' | ':' | '*' | '|' | '\"' | '^' | '+' | '='

to avoid problems with invalid file names.

It should be possible to allow cpdf, optionally, to convert the name to UTF8, so it might be used as a filename. But this would need some investigation. It might, of course, depend on the platform.

If you're a commercial customer, we can look into this now for you. Otherwise, it will have to go on the list of issues for a future release.

**Comment by johnwhitington** [comment]
Another option is to extract the bookmarks in JSON format:

$ cpdf -list-bookmarks-json New.pdf 
[
  { "level": 0, "text": "封面", "page": 1, "open": false,
  "target": [ { "I": 1 }, { "N": "/FitH" }, { "F": 844.0 } ] }, { "level": 0,
  "text": "目录", "page": 3, "open": false,
  "target": [ { "I": 3 }, { "N": "/FitH" }, { "F": 805.0 } ] }, { "level": 0,
  "text": "前言", "page": 5, "open": false,
  "target": [ { "I": 5 }, { "N": "/FitH" }, { "F": 767.0 } ] }, { "level": 0,
  "text": "内容", "page": 6, "open": false,
  "target": [ { "I": 6 }, { "N": "/FitH" }, { "F": 906.0 } ] }

Then you can do the renaming of the files yourself, in a script.

**Comment by johnwhitington** [comment]
Also available without JSON, but remember to add `-utf8` to the command line:

$ cpdf -list-bookmarks New.pdf -utf8
0 "封面" 1 "[1/FitH 844]"
0 "目录" 3 "[3/FitH 805]"
0 "前言" 5 "[5/FitH 767]"
0 "内容" 6 "[6/FitH 906]"

**Comment by lyscop** [comment]
Yeah, I get the list of bookmarks when adding `-utf8`.

But still can't get the right name after splitting the file, I now want the after splitting file name to be 封面.pdf  目录.pdf  前言.pdf  内容.pdf

```
cpdf.exe -split-bookmarks 0 "C:\Users\Administrator\Desktop\New.pdf" -utf8 -o C:\Users\Administrator\Desktop\@B.pdf
```

Thank you for introducing the constructs of the cpdf. I usually to processing word work personally, and I use Adobe Acrobat for long days by click click to split a PDF, and it is more efficient to use the command line.

**Comment by johnwhitington** [comment]
Yes, that's right. As I explain in my comment above, cpdf can't currently do what you want. I'll leave the bug report open for the future, though.

**Comment by lyscop** [comment]
> UTF8, so it might be used as a filename

Oh, I see, you may mean this that can't be as the name.

Hope to get a solution as possible.

From now on, this is probably the best command line tool for PDF, especially that provide paid ones.

**Comment by johnwhitington** [comment]
It turns out this was easy to fix. Please try this new version of cpdf (for Windows):

https://www.coherentpdf.com/tmp/3rdApril2022.zip

Here is what I get:

```
$ cpdf -split-bookmarks 0 New.pdf -utf8 -o @B.pdf
$ ls
New.pdf		内容.pdf	前言.pdf	封面.pdf	目录.pdf
```

Just add `-utf8` to your command line with this new version.

**Comment by lyscop** [comment]
Wow, it works nice. Now it can be totally instead the [SplitPDF.jar](https://sourceforge.net/projects/splitpdf/) and without the Java environment.

Thank you for your great job.
