### ISSUE TITLE
Quick documentation correction for -scale-page

### ISSUE THREAD

**Issue by jaimet** [johnwhitington/cpdf-source#249]
Hi.

On page 16 of the [pdf cpdf manual](https://www.coherentpdf.com/cpdfmanual.pdf), it says:

`cpdf -scale-page "2 2" in.pdf -o out.pdf`
Convert an A4 page to A3, for instance.

That command won't convert an A4 page to A3. It will convert an A4 page to A2.

HTH, J (PS thanks again for writing cpdf).

**Comment by johnwhitington** [comment]
Good catch. Fixed. Thanks!
