### ISSUE TITLE
Is possible to merge one PDF to a certain place in another PDF

### ISSUE THREAD

**Issue by VictorAtGH** [johnwhitington/cpdf-source#251]
I would like to know whether it possible with the Coherent PDF Command Line Tools to do the following:

1. I have an existing PDF with 10 pages (PDF-1)
2. To merge into PDF-1 another PDF (PDF-2), but
3. Merge PDF-2 into PDF-1 starting at page 5 of PDF-1?

Rather than simply merging the two together or just a select number of pages together.

Any help with this would be gratefully received.

**Comment by johnwhitington** [comment]
You can simply do:

`cpdf pdf1.pdf 1-5 pdf2.pdf pdf1.pdf 6-end`

CPDF will recognise that the two uses of pdf1.pdf are the same file, so there will be no duplication or bloating of the output.
