### ISSUE TITLE
`-squeeze` should log to stderr instead of stdout

### ISSUE THREAD

**Issue by agguser** [johnwhitington/cpdf-source#252]
, to not interfere when using `-stdout`.

Also, `-squeeze-log-to /dev/stderr` causes "Illegal seek" error.

**Comment by johnwhitington** [comment]
Could you tell me your operating system please?

**Comment by agguser** [comment]
Linux 5.19.1

**Comment by johnwhitington** [comment]
Thanks. Here on MacOS it has a different mode of failure - it just outputs to stdout even with -squeeze-log-to. So there is a problem.

I won't change the existing default behaviour (without -squeeze-log-to) for the reason of backward compatibility. But -squeeze-log-to in conjunction with stderr needs fixing.

For now, I'm afraid you will have to log to a temp file and then delete it.

Marking for 2.6.

**Comment by johnwhitington** [comment]
See #311
