### ISSUE TITLE
Could it convert some images like PNG or JPG to a new PDF file?

### ISSUE THREAD

**Issue by lyscop** [johnwhitington/cpdf-source#257]
I sometimes need to add some images to a new file, and I used to add the images in Acrobat, but I think it is complex that I need to open the program and select the images and add all of them.

If there is a Command line to auto add the images from a folder to a new PDF, it will convenient.

I scan the CPdf command line, and it seems there is no one to deal with the image locally.

**Comment by johnwhitington** [comment]
Cpdf only knows how to process existing PDF files. It doesn't (yet) convert formats.

If you want to use cpdf to stamp a PNG on a PDF file, you'll need to convert the PNG to a PDF first. Then, you can use `-stamp-on` to stamp that new PDF onto another one.
