### ISSUE TITLE
draft option finds the text and makes the file searchable, but the text can't be seen

### ISSUE THREAD

**Issue by davbac** [johnwhitington/cpdf-source#260]
I'm trying to remove all the images and background from a PDF file. Using a OCR tool I've been able to create the text; then with
`cpdf -draft` I have removed the images.

The problem is, the text seems to be placed underneath the white background, since passing the output through
 `cpdf -blacktext` does not make any difference.

I have searched the manual, but I haven't found any reference to commands that change the z-ordering of layers.
Did I just miss the right command, is there some other way to do this, or am I just missing some vital information?

**Comment by johnwhitington** [comment]
There is no direct manipulation of existing content in cpdf, except for very specific tools like -draft, -blacktext etc.

You can export the PDF file to JSON like this:

`cpdf in.pdf -output-json -output-json-parse-content-streams -o out.json`

Then, remove the offending white rectangle, then round-trip back to  a PDF with

`cpdf -j out.json -o out.pdf`

If you get stuck, feel free to attach an example file here, or if it's private, send it to contact at coherentgraphics dot co dot uk.

**Comment by johnwhitington** [comment]
Oh, another possibility is this: your OCR program uses invisible text, by setting the text rendering mode to invisible, not by making it white. In this case, -blacktext should be fixed to remove the instructions which set the text rendering mode to invisible.

Please do supply the file and I can investigate...

**Comment by davbac** [comment]
The file I was working with was quite big, so I'll just put this old train ticket as example, as the problem presents itself in the same way; here are the original pdf and OCR output, plus the output of draft
[ocr'd.pdf](https://github.com/johnwhitington/cpdf-source/files/10409507/ocr.d.pdf)
[original.PDF](https://github.com/johnwhitington/cpdf-source/files/10409509/original.PDF)
[draft.pdf](https://github.com/johnwhitington/cpdf-source/files/10409542/draft.pdf)

I just tried looking into the json file but to be honest I have no idea which element would be supposed to be the rectangle, or how to change the text setting.

(Sorry for the delay, Europe timezone here)

**Comment by johnwhitington** [comment]
Thanks. I'll look at this in the morning (I'm usually in the UK, but I'm in Japan at the moment, so I barely know which way is up timezone-wise at the moment).

**Comment by johnwhitington** [comment]
I'm afraid you are out of luck. The OCR software generates the font metadata, so that you can copy & paste from the file, but includes a font with no glyphs (to save space), so there are simply no glyphs to show, even if we make the text black.

**Comment by davbac** [comment]
Thanks a lot for your help.
Using the famous science adage "F**k around and find out" I've discovered that this problem can actually be (partially) solved by opening the pdf in LibreOffice Draw and just hitting the "export as pdf" button.
The document structure is lost but at least it's readable.
Gonna mark the issue as solved
