### ISSUE TITLE
How to remove objects in a certain region?

### ISSUE THREAD

**Issue by prRZ5F4LXZ** [johnwhitington/cpdf-source#268]
I want to remove objects that appear in the same region in all the pages of a pdf file. Is there a way to do so with cpdf?

**Comment by johnwhitington** [comment]
No. But the search term you are looking for is "redaction". Hope this helps...

**Comment by prRZ5F4LXZ** [comment]
I don't find "redaction" in cpdf manual. I am not sure why you mention. I am looking for removing the object not just redacting the object.

**Comment by johnwhitington** [comment]
As I said, cpdf does not do redaction, so you won't find it in the manual.

Redaction is removal of material. Sometimes a black rectangle is put over the top, to show it has been redacted, but the redaction itself is the actual removal.

So, cpdf won't help you, and you need to search Google for "PDF redaction" or similar.

**Comment by prRZ5F4LXZ** [comment]
I don't think "pdf redaction" is an appropriate key word to search. Redaction in the context of pdf clearly means that readers still can see something is covered up.

https://www.adobe.com/acrobat/resources/how-to-redact-a-pdf.html

https://www.merriam-webster.com/dictionary/redact

Although "redact" has two meanings "obscure" or "remove", I never see it is used as "remove". I only see it is used as "obscure" in the context of pdf.

https://www.merriam-webster.com/dictionary/redact

"to obscure or remove (text) from a document prior to publication or release"

**Comment by johnwhitington** [comment]
In Acrobat, you can set the redaction colour to "None". Objects will be removed, as with any other kind of redaction, but no rectangle is put over the top.
