### ISSUE TITLE
squeeze in current dev duild 16th FEB 2023 vs cpdfsqueeze

### ISSUE THREAD

**Issue by maadjordan** [johnwhitington/cpdf-source#269]
[kemehe.pdf](https://github.com/johnwhitington/cpdf-source/files/10773729/kemehe.pdf)
Please check this file with the current developed built (16th Feb 2023) againest cpdfsqueeze. cpdfsqueeze result is way smaller and when later processed with pdfsizeopt got even smaller while resulted file after current build version uis larger andfails to work with pdfsizeopt.

**Comment by johnwhitington** [comment]
Yes, something very strange is going on here. Clearly a regression from v2.5.1:

```
cheddar:Downloads john$ cpdf -squeeze kemehe.pdf -o out.pdf
Initial file size is 6285507 bytes
Beginning squeeze: 3358 objects
Squeezing... Down to 1905 objects
Squeezing page data and xobjects
Recompressing document
Final file size is 11475932 bytes, 182.58% of original.
cheddar:Downloads john$ open out.pdf
```

```
cheddar:Downloads john$ cpdf2.5.1 -squeeze kemehe.pdf -o out.pdf
Initial file size is 6285507 bytes
Beginning squeeze: 3358 objects
Squeezing... Down to 1905 objects
Squeezing page data and xobjects
Recompressing document
Final file size is 5783926 bytes, 92.02% of original.
```

**Comment by maadjordan** [comment]
also speed is slower

**Comment by johnwhitington** [comment]
Fixed.
