### ISSUE TITLE
Beta Version

### ISSUE THREAD

**Issue by maadjordan** [johnwhitington/cpdf-source#281]
Is it possible to keep getting an updated beta version in monthly or bi-monthly or what ever suitable.

Many Thanks

**Comment by johnwhitington** [comment]
You will have to build from source I'm afraid. The tip-of-trunk cpdf is always buildable against the tip-of-trunk camlpdf.

v2.6 is a big upgrade, with some invasive internal changes, so there is no guarantee of stability in the development version.
