### ISSUE TITLE
Add a feature to actually remove text -- the opposite to -draft

### ISSUE THREAD

**Issue by hussainb** [johnwhitington/cpdf-source#4]
hello ,

I have a pdf which has unicode text, I am trying to strip out all the fonts in the pdf using  -remove-fonts option so that only the image objects remain. I get partial success in doing that. i.e the fonts turn into blobs and adobe acrobat complains "Cannot find or create the font 'AKKUUO+ChiruthaHeavy'.Some characters may not display or print correctly ".

ScreenShot of Converted pdf after using the command `cpdf -remove-fonts in.pdf -o out.pdf`.

![image](https://f.cloud.github.com/assets/4962633/1805695/499daac6-6c8d-11e3-9103-a6b0589a0b42.png)

ScreenShot of the above corrupt pdf after converting it into an image using imageMagick/GhostScript.

![image](https://f.cloud.github.com/assets/4962633/1805707/b82e5ff8-6c8d-11e3-9733-d0c209c0d19c.png)

**Comment by johnwhitington** [comment]
Wish granted in forthcoming v2.3
