### ISSUE TITLE
add/modify annotations

### ISSUE THREAD

**Issue by ghennequin** [johnwhitington/cpdf-source#47]
Is there any plan to support addition/modification of annotations in the near future? I wouldn't mind contributing but I don't really know where to start.

**Comment by johnwhitington** [comment]
It's unlikely to happen soon.

Essentially, you would need to complete the unfinished function add_annotation in the pdfannot.ml file in the CamlPDF repo:

https://github.com/johnwhitington/camlpdf/blob/master/pdfannot.ml

And then, plumb it into cpdf, with an appropriate command line representation.

**Comment by johnwhitington** [comment]
Done in v2.6. Can now extract annotations to JSON, modify them, and then re-apply them.
