### ISSUE TITLE
feature suggestion for cpdf: diff

### ISSUE THREAD

**Issue by UnixJunkie** [johnwhitington/cpdf-source#57]
A diff of pdf files would be nice.

I think a simple version would be to extract the text of both
PDFs, then highlight the delta in an output pdf.

For example:
cpdf -diff previous.pdf current.pdf -o prev_plus_delta.pdf

the output would be previous.pdf plus the deltas to convert its
text into current.pdf shown with some colors.

**Comment by johnwhitington** [comment]
Closing, since it's been a long time, and text extraction is not on the agenda.
