### ISSUE TITLE
Option -no-stderror to suppress standard error output

### ISSUE THREAD

**Issue by BuckSFUK** [johnwhitington/cpdf-source#59]
It would be great to be able to optionally suppress error output, especially in cases where there are exhaustive warnings returned.

**Comment by johnwhitington** [comment]
Is there a reason you can't just redirect stderr to null? I.e on Windows `>nul` or Unix `>/dev/null`

**Comment by johnwhitington** [comment]
See also https://github.com/johnwhitington/camlpdf/issues/56 in CamlPDF
