### ISSUE TITLE
Must all input.files end in pdf?

### ISSUE THREAD

**Issue by andre16354** [johnwhitington/cpdf-source#61]
In linux land this is not customary, I want to be able to use any kind of filename. Moreover, as the 
command 'cpdf -split in.pdf -o %%%'  splits the document 'in.pdf' in 001 002 003 .... I would like to be able to 'cpdf [-merge] 003 004 007 008 -o ThesePageHaveIt,pdf'. I've (briefly) browsed through the sources...  An option to process ALL file would be nice, or am I  missing something?

**Comment by johnwhitington** [comment]
You can use -i to use any file (see Section 1.1 of the manual). The reason for this is to distinguish file names and ranges. If I write...

```
cpdf a.pdf 3 -o out.pdf
```
...do I mean select page 3 of `a.pdf`, or do I mean "merge the PDF files `a.pdf` and `3`"?

The `-idir` option reads all the files in a directory, regardless of their names.

**Comment by andre16354** [comment]
> You can use -i to use any file (see Section 1.1 of the manual). The reason
> for this is to distinguish file names and ranges. If I write...
>
> ```
> cpdf a.pdf 3 -o out.pdf
> ```
> ...do I mean select page 3 of `a.pdf`, or do I mean "merge the PDF files
> `a.pdf` and `3`"?
>
> The `-idir` option reads all the files in a directory, regardless of their
> names.
>

Hmmm odd, if I do 'cpdf 004 005 006 007 -o this.pdf' it throws an error at
me... (there must be an input (pdf??)file).


004, 003 ... are separate pdf pages....

--
               Andre van der Vlies <andre@vandervlies.xs4all.nl>
               Certifiable Linux/UNIX engineer (CLUE)
               Homepage: http://vandervlies.xs4all.nl/~andre
Key fingerprint = 397C 7479 67DB 9306 23DC B423 7B58 CD5A 6EFF 5CF8
--
    'Reality is that which, when you stop believing in it, doesn't go away.'
                    -  Philip K. Dick
    'Any sufficiently advanced technology is indistinguishable from magic.'
                    - Arthur C. Clarke

    ^[^#]
--

**Comment by johnwhitington** [comment]
You would expect that to be the case, since they would be interpreted as ranges, not PDF files -- see my previous comment for the explanation.

You need

```
cpdf -i 004 -i 005 -i 006 -i 007 -o this.pdf
```

**Comment by andre16354** [comment]
> You would expect that to be the case, since they would be interpreted as
> ranges, not PDF files -- see my previous comment for the explanation.
>
> You need
>
> ```
> cpdf -i 004 -i 005 -i 006 -i 007 -o this.pdf
> ```
>

Ah... Ok, my bad... Just had a different reasoning.


ThanX!


--
               Andre van der Vlies <andre@vandervlies.xs4all.nl>
               Certifiable Linux/UNIX engineer (CLUE)
               Homepage: http://vandervlies.xs4all.nl/~andre
Key fingerprint = 397C 7479 67DB 9306 23DC B423 7B58 CD5A 6EFF 5CF8
--
    'Reality is that which, when you stop believing in it, doesn't go away.'
                    -  Philip K. Dick
    'Any sufficiently advanced technology is indistinguishable from magic.'
                    - Arthur C. Clarke

    ^[^#]
--
