### ISSUE TITLE
-add-text not working with Unicode

### ISSUE THREAD

**Issue by darrrk** [johnwhitington/cpdf-source#63]
If I add some unicode text in `-add-text` param, in outputed pdf unicode characters are stripped.
`-utf8`, `-raw` not working for this situation.

**Comment by johnwhitington** [comment]
cpdf adds text using the standard 14 Postscript fonts, so only characters which happen to be defined in those fonts can be used. This means accented characters, for example, are likely to work, but you can't expect any old unicode codepoint to map to a glyph.

What characters were you trying to add?

**Comment by darrrk** [comment]
Cyrillic characters, as "б г я э" e. t. c

**Comment by johnwhitington** [comment]
The standard fonts are Latin only I'm afraid. At the moment, cpdf doesn't know how to embed fonts in a PDF. However, you can use the -copy-font mechanism to cherry-pick a cyrillic font from another document... Then use -add-text with that font.

**Comment by darrrk** [comment]
Ok, thanks
