### ISSUE TITLE
Adding Image compression and optimizing

### ISSUE THREAD

**Issue by maadjordan** [johnwhitington/cpdf-source#67]
First I would like to thank you for your effort in making cpdf and smpdf and issue a special community version and i would to ask for a request to add image compression and optimizing by the following methods:
1- LZW streams to be converted to Deflate through well optimized version like "Leanify" at https://github.com/JayXon/Leanify.
2- PNG streams to be optimized "Truepng" at http://x128.ho.ua/pngutils.html and then "Leanify"
3- JPG streams to be optimized with "jpeg-recompress" at https://github.com/danielgtaylor/jpeg-archive using "smallfry" method and mozjpeg at https://github.com/mozilla/mozjpeg. or "Leanify"
4- lossless JPEG2000 can go through "Truepng" then packit again as jpeg2000 or png (always stream will be smaller).
5- CCITT or RLE streams to be converted into JBIG2 with "jbig2enc" at https://github.com/agl/jbig2enc (an old compiled version can be found here http://soft.rubypdf.com/software/windows-version-jbig2-encoder-jbig2-exe. (note that lossless compression is highly recommended due lossy might mix up alphabets like "O" "0"_
6- flash streams (SWF) can go through "Leanify" too. (BTW these files mostly has malicious code)
7- attachments streams can go through "Leanify" as it may optimize size prior repacking.
8- regarding 3d data still i know nothing about it. sorry.

**Comment by johnwhitington** [comment]
Thanks for enumerating all these options carefully.

I don't think it's likely I will build these things directly into the software (i.e build the software with these libraries), but we could have command line options to direct cpdf to send particular kinds of data via these command line tools and read them back in).

**Comment by maadjordan** [comment]
doing these steps through command line is better. I could not find a command line to do such steps. can we do it with current cpdf version?

**Comment by necros2k7** [comment]
+1 for idea
