### ISSUE TITLE
Compile error - Error: Unbound module Pdfutil

### ISSUE THREAD

**Issue by rehanog** [johnwhitington/cpdf-source#81]
Same error either on v2.1.1 or on master (9c71623). On Ubunt 14.04, already did opam install camlpdf

ocamlfind ocamlc -package camlpdf -c -annot xmlm.mli
ocamlfind ocamlopt -package camlpdf -c -annot -g -w -3 -annot xmlm.ml
ocamlfind ocamlc -package camlpdf -c -annot cpdfstrftime.mli
ocamlfind ocamlopt -package camlpdf -c -annot -g -w -3 -annot cpdfstrftime.ml
File "cpdfstrftime.ml", line 2, characters 0-12:
Error: Unbound module Pdfutil
make[1]: *** [cpdfstrftime.cmx] Error 2

**Comment by johnwhitington** [comment]
Can you confirm that you (or OPAM) installed CamlPDF v2.1.1? The versions of Camlpdf and cpdf must match.
