### ISSUE TITLE
Malformed PDF produces error not found in source—how to proceed?

### ISSUE THREAD

**Issue by egeriis** [johnwhitington/cpdf-source#83]
Hi!

We're having some issues where cpdf give us an error when it meets a malformed PDF:

```
Attempting to reconstruct the malformed pdf ab5308ef-610e-4452-8cd0-dbd516f3e417_tmp.pdf...
list length 0
cpdf encountered an error. Technical details follow:

Failed to read PDF - initial error was
Pdf.PDFError("Could not read PDF header whilst reading file ab5308ef-610e-4452-8cd0-dbd516f3e417_tmp.pdf at position 1032")

final error was
Pdf.PDFError("Could not read PDF header whilst reading file ab5308ef-610e-4452-8cd0-dbd516f3e417_tmp.pdf at position 1032")

 whilst reading file ab5308ef-610e-4452-8cd0-dbd516f3e417_tmp.pdf at position 1032
```

I am trying to figure out how to solve this issue. First of all, the file is readable by Preview on macOS and pdf.js, so I reckon there should be some kind of solution.

But looking for this particular error, not much is found, and it doesn't appear that this error message is found anywhere in the source code.

Do you guys have any recommendation for how I could proceed to find some resolution to this issue?

**Comment by johnwhitington** [comment]
Please supply the file, and I can take a look...

**Comment by johnwhitington** [comment]
Also please give cpdf -version

**Comment by egeriis** [comment]
I am afraid I am unable to supply the file as it contains sensitive information about my customer. What can I do to help here?

```
$ bin/cpdf -version
cpdf Version 2.1 (26th November 2014)
```

Tried with newest version too, though. 

```
$ cpdfdemo/cpdf -version
This demo is for evaluation only. http://www.coherentpdf.com/
cpdf Version 2.2 (build of 9th January 2017)
```

**Comment by johnwhitington** [comment]
A PDF must have "%PDF-1.x" somewhere in its first 1024 bytes. It may have custom data before that. This is the header. My guess is yours has more than 1024 bytes of custom data or junk. (Actually, an ISO standard PDF must have no such data, but it was formerly allowed).

Try this ghostscript command:

`gs -dBATCH -dNOPAUSE -sDEVICE=pdfwrite -sOutputFile=output_filename.pdf input_filename.pdf`

Ghostscript is pretty good at error messages -- does it give a warning or error?. If ghostscript works to strip the junk, you could use it to pre-process your files before giving them to cpdf.

Can you look at the original file in a text editor to confirm it has junk before the header?

If you're a potential paying customer, we could fix cpdf to accept such malformed files, but we would need you to find an example you can send us. You can email me directly at john at coherentgraphics dot co dot uk if that is the case.

**Comment by egeriis** [comment]
I reckon we've already purchased a license. But I think I've found the issue, they actually appear to be JPEG files w/`.pdf` extension. So then it makes sense for cpdf not to recognize the file.

**Comment by johnwhitington** [comment]
Great. Glad it's fixed!

**Comment by egeriis** [comment]
Thank you for your assistance @johnwhitington
