### ISSUE TITLE
Convert/ Insert/ Replace Image streams

### ISSUE THREAD

**Issue by maadjordan** [johnwhitington/cpdf-source#84]
Is it possible to add ability to convert existing images (JPG,JPEG200, JBIG2,..etc) directly to PDF. 
Also ability to insert/replace existing image streams with images of same format.

**Comment by maadjordan** [comment]
any update

**Comment by johnwhitington** [comment]
Convert single or multiple JBIG2 files to PDF (lossless and lossy) coming in v2.7. Image-roundtripping coming in v2.7.
