### ISSUE TITLE
Additional optimizations features

### ISSUE THREAD

**Issue by maadjordan** [johnwhitington/cpdf-source#85]
I've notice that pdfenhancer can detect and remove more unnecessary elements of pdf. I;ve test it on cpdfmanual.pdf of v2.2 and good the following result (and after running -squeeze command it saved little due the simple pdf structure. but I managed to get more on larger and complex files):
[cpdfmanual.pdf](https://github.com/johnwhitington/cpdf-source/files/706457/cpdfmanual.pdf)
[cpdfmanual-output.pdf](https://github.com/johnwhitington/cpdf-source/files/706458/cpdfmanual-output.pdf)

Processing file 'D:\CPDF\cpdf-binaries-master_v2.2\cpdf-binaries-master\cpdfmanual.pdf'
Created file 'D:\CPDF\cpdf-binaries-master_v2.2\cpdf-binaries-master\cpdfmanual-output.pdf'
   Starting size = 219.4 KB (224,645 Bytes)
   Ending size =  220.9 KB (226,234 Bytes)
   Percent growth = 0.71%
   Optimized and compressed 1 Form XObject out of 1 total
   Removed 70 Page Boxes
   Removed 71 ProcSets
   Removed Tagging
   Removed 2 of 2 Marked Content elements
   Changed the color of 2 of 4 Color Content Operators
   Optimized 71 Content Streams
   Wrote PDF 1.5+ Compressed Objects
   Synchronized Info dictionary with XMP metadata.
   Set the Page Mode
   Set the Page Layout
   Set the Open Destination
Elapsed Time 1.02 seconds
Success

Is there a way to same with current v2.2 I've tried several commands but could not manage to get benefit

**Comment by johnwhitington** [comment]
Stripping option many things (procsets, thumbnails etc.) planned for v2.8. Thanks.
