### ISSUE TITLE
current version (2017/02/05) doesn't compile with ocaml-4.04.0

### ISSUE THREAD

**Issue by HJarausch** [johnwhitington/cpdf-source#88]
Hi,
I don't know Caml (ocaml) and cannot fix the following error which I get when I try to compile cpdf-source

ocamlfind ocamlopt -package camlpdf -c -annot -g -w -3 -annot cpdf.ml
File "cpdf.ml", line 302, characters 12-37:
Error: This function has type
         string option -> string option -> Pdfio.input -> Pdf.t
       It is applied to too many arguments; maybe you forgot a `;'.

Many thanks for your help,
Helmut

**Comment by johnwhitington** [comment]
Your camlpdf and cpdf-source repos must have identical version numbers. 2.1 and 2.1, trunk and trunk etc.
